README.md
Adds LiveView documentation to README.md
Tackles Jira AP-487.
Needs a new deploy of `apify-web` because screenshots are served from there.
They are already pushed into `develop`.
=> Add live view documentation

CHANGELOG.md, package.json, src/dataset.js, test/dataset.js
Implements https://github.com/apifytech/apify-js/issues/70
Replaces https://github.com/apifytech/apify-shared-js/pull/5
Minor change in `apify-client` is necessary to accept pre-serialized values.
=> Add max data size validation and chunking to dataset.pushData()

CHANGELOG.md, src/basic_crawler.js, src/cheerio_crawler.js, src/puppeteer_crawler.js, test/autoscaling/snapshotter.js
`PuppeteerCrawler` misses the change to use `autoscaledPoolOptions` so this implements it.
`CheerioCrawler` has a wrong implementation of `requestFunction` so this fixes it.
- We still need to decide which status codes in the `requestFunction` are gonna reject and where to place this logic. I suggest reject all >=500.
=> Some additional changes following up AutoscaledPool

src/request_queue.js, test/request_queue.js
Hello,
Thought I'd help with improving the flexibility of `RequestQueue.addRequest` with an overload that accepts an object to construct a `Request`.
I haven't updated project-related documentation (i.e. README.md) or versioning as I'm unsure whether that's something left to maintainers to aggregate.
=> Add RequestQueue overload for adding requests

src/request_queue.js, test/request_queue.js
But reported by @metalwarrior665
=> Fixing bug where duplicate already handled requests added with forefront were returned in fetchNextRequest()

docs/api/Request.md, src/request.js, test/request.js
One of users reported an "error" in one of their actors that was quite impossible to debug, due to the error being swallowed by a `TypeError` thrown from `request.pushErrorMessage`, since apparently the "error" passed to it was neither an instance of `Error`, nor a `String`.
This PR removes this `TypeError` and instead implements a set of type checks that attempt to extract infomation from all possible arguments that may have been passed `request.pushErrorMessage`.
This is useful in two ways. First of all, it improves the debugging experience. Secondly it prevents the possible `TypeError` from crashing the `AutoscaledPool` by rejecting a `runTaskFunction()` promise.
=> Improve the logging of request.pushErrorMessage

src/puppeteer_utils.js, test/puppeteer_utils.js
The `Apify.utils.puppeteer.enqueueLinks()` function does not support seeding the resulting `Request`s with custom `request.userData`. It's only possible to do it via the `pseudoUrls`, but that doesn't provide flexibility when it's necessary to extend only specific `Request`s and not all of them that were captured by a specific Pseudo URL.
This PR adds a `userData` parameter to the function that takes precedence over any previous `request.userData` and seeds the `Request`. It also moves away from individual arguments to an options object.
=> Add userData to enqueueLinks

CHANGELOG.md, src/dataset.js, test/dataset.js
`datasetLocal.getData()` now correctly returns `[]` for an overflowing offset.
Fixes: https://github.com/apifytech/apify-js/issues/250
=> Fix overflowing offset in local dataset

package.json, src/cheerio_crawler.js, src/puppeteer_crawler.js, src/puppeteer_live_view_server.js, src/utils.js, test/actor.js, test/autoscaling/snapshotter.js, test/events.js, test/puppeteer.js, test/puppeteer_live_view_server.js, test/utils.js, test/webdriver.js
Open timeout promises would prevent garbage collection of the data promises and kept the process running. This PR adds a new function that wraps the data promises so that the timeouts automatically cancel, plus it fixes some hanging issues in the tests, except `Apify.launchWebDriver`, that still hangs due to `proxy-chain` not being closed.
It also fixes some unrelated flaky tests.
=> Fix hanging timeouts in Cheerio and PuppeteerCrawler

CHANGELOG.md, src/basic_crawler.js, src/request_queue.js, test/basic_crawler.js, test/request_queue.js
`BasicCrawler` keeps a `handledRequestsCount` of handled requests. However, this number always started at `0`, so after migration or after restarting actor locally, the actual values from storages would not be used. This PR enforces this check on every `basicCrawler.run()`.
=> Load handledRequestCount from storages

CHANGELOG.md, src/basic_crawler.js
Tackles https://github.com/apifytech/apify-js/issues/223
All Crawlers are based on `BasicCrawler`, which will finish when either the underlying `AutoscaledPool` finishes or when an error is thrown. We already log errors, so that's a non-issue. It can also be aborted, but we already log that too.
The `AutoscaledPool` finishes when the `isFinishedFunction` returns true. In `BasicCrawler`, it can be either the default function or a custom function. Both now have new log messages. Reaching max requests is also handled.
So I reckon that's all. If you have any other ideas, let me know.
=> Add log messages to inform about the reasons why a crawler finished

CHANGELOG.md, src/puppeteer_crawler.js, src/puppeteer_pool.js, test/puppeteer_pool.js
Implements tab reuse in `PuppeteerPool` to hopefully improve `PuppeteerCrawler` performance under high loads (and also enable single tab live view)
Let me know if you think there should be more tests.
Issue: https://github.com/apifytech/apify-js/issues/237
=> Reuse tabs in PuppeteerCrawler

CHANGELOG.md, src/puppeteer_crawler.js, src/puppeteer_pool.js, test/puppeteer_pool.js
`reusePages` option was missing from `PuppeteerCrawler` and therefore could not be used. It was also leaking memory because browsers were not being closed due to open idle pages. This PR fixes both issues.
=> Fix reusePages

CHANGELOG.md, src/enqueue_links.js, test/enqueue_links.js
Browsers automatically resolve relative links, therefore when `enqueueLinks()` encounters relative links with Puppeteer, it's a non-issue.
This is not true for Cheerio though, since it has no information about the necessary base URL. This PR adds a `baseUrl` option to `enqueueLinks()` so that user can input this `baseUrl` manually.
The function will now throw when Cheerio is used, a relative URL is found and no `baseUrl` is provided. (It would fail later anyway, when the crawler would try to open the URL)
**Expected Usage:**
```js
async function handlePageFunction({ $, request, response }) {
// ...
await Apify.utils.enqueueLinks({
$,
requestQueue,
baseUrl: response.request.uri.href
})
// ...
}
```
The `response.request.uri.href` is quite a mess, so I figure we should also add a …
=> Enable relative links resolution in enqueueLinks with Cheerio

CHANGELOG.md, src/basic_crawler.js, src/cheerio_crawler.js, src/pseudo_url.js, src/puppeteer_crawler.js, src/request.js, src/request_list.js, src/utils.js, test/autoscaling/snapshotter.js, test/cheerio_crawler.js, test/utils.js
This PR automatically adds a `loadedUrl` property to `Request` before the `handlePageFunction` is invoked.
It's very simple and does not care about meta or JS redirects in `PuppeteerCrawler`.
I also added some docs improvements and reduced default `handlePageFunction` timeouts to 60s from 300s, because it's always been pretty annoying to have requests hanging for 5 minutes. That's a breaking change probably, though.
=> Add Request.loadedUrl

src/key_value_store.js, src/request_queue.js, test/_helper.js, test/key_value_store.js, test/request_queue.js
* there was bug in retrying of getHead() requests in request queue to ensure consistency when (Date.now() - queue.modifiedAt < 10s)
* there were multiple bugs in key value store causing unhandled promise rejections when running tests
* I also updated tests to exit with 1 on any unhandled promise rejection
=> Request queue and key-value store fixes

CHANGELOG.md, src/basic_crawler.js, src/cheerio_crawler.js, src/constants.js, src/puppeteer.js, src/puppeteer_crawler.js, src/puppeteer_pool.js, src/utils.js, test/actor.js, test/basic_crawler.js, test/cheerio_crawler.js, test/puppeteer_pool.js, test/utils.js
This should resolve the trouble where a hanging `browser.newPage()` would hang request processing to the point where the actor would be left with 1 or 2 unprocessed requests and would never shut down.
- adds a timeout to `BasicCrawler`
- other Crawlers now set this timeout to 2x their timeouts
- adds timeout to puppeteer invocations in `PuppeteerPool`
- removes some deprecations and TODOs
=> Add timeouts to puppeteer operations (and other fixes)

.eslintrc.json, src/puppeteer_live_view_client.js, src/puppeteer_utils.js, test/.eslintrc.json, test/puppeteer_utils.js
Implementing by adding a test-specific `.eslintrc.json` that defines all the mocha globals for test files only and then fixing manually all the other errors.
=> Add no-undef rule to eslint

src/puppeteer_crawler.js, src/puppeteer_utils.js, test/puppeteer_utils.js
Since request interception in Puppeteer disables cache, which leads to sub-optimal performance, I disabled the automatic inclusion of it in `PuppeteerCrawler` (with `gotoExtended`), replaced `blockResources` with a similar `blockRequests` function that does not use interception and added notes and warnings to all the functions that use it.
=> Limit use of request interception

src/crawlers/puppeteer_crawler.js, src/live_view/live_view_server.js, src/puppeteer_pool.js, test/puppeteer_pool.js
A user complained that it takes too long for live view to show first snapshot. This PR attempts to shorten the time to first snapshot by taking the snapshot right after navigation, instead of when the page is closing.
The snapshot is also being taken in parallel with `handlePageFunction` execution so by the time it finishes, it might already be done. If not, it is awaited before page close.
=> Faster live view

src/puppeteer.js
This second log is almost the same but doesn't have the whole proxy URL. I don't know where you want the log to be.
Compare 
```
2019-09-25T11:46:43.190Z INFO: Launching Puppeteer {"args":["--no-sandbox","--user-agent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0 s=0.8617189793878433"],"headless":true,"defaultViewport":{"width":1366,"height":768},"pipe":true,"proxyUrl":"http://session-0.8617189793878433:<redacted>@172.31.62.80:8011/"}
2019-09-25T11:46:43.454Z INFO: Launching Puppeteer {"args":["--no-sandbox","--user-agent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0 s=0.8617189793878433","--proxy-server=http://127.0.0.1:32482"],"headless":true,"defaultViewport":{"width":1366,"height":768},"pipe":true}
```
=> Removed duplicate Puppeteer launch log

src/crawlers/cheerio_crawler.js
Hi,
i didn't find the option `requestFunction` in `CheerioCrawler` initialization docs and also in code so
this removes mention of in docs for `ignoreSslErrors`.
Cheers
=> Remove nonexistant option mention from docs [skip ci]

src/puppeteer_utils.js
Constant was not propagated into page.evaluate. It crashed only on specific sites (youtube.com) therefore tests didn't cover it
=> fix infinite scroll

package.json, src/utils.js
Since we now support Node 10 and up, we don't need `xregexp` for unicode property escapes anymore.
=> Remove xregexp dependency

docs/api/Dataset.md, src/dataset.js
Dataset.getData() return value was not documented properly.
=> [docs] Updated Dataset.getData() JSDoc to include the `count` property

docs/api/puppeteer.md, src/puppeteer_utils.js
Providing a `boolean` crashes on runtime
=> fix parameter type on utils.puppeteer.blockRequests

package.json
the folder is needed for "local" types of external apify modules
=> needs to include types-apify, fix log as `any`

src/session_pool/session_pool.js
I think it would not be good to catch the `createSessionFunction` by default.
=> [DOCS] Added error warning to docs.

README.md, docs/guides/data_storage.md, docs/guides/environment_variables.md, docs/guides/getting_started.md, docs/guides/motivation.md, docs/guides/puppeteer_live_view.md, docs/readme/overview.md, examples/call_actor.js, examples/puppeteer_with_proxy.js, examples/screenshots.js, src/crawlers/puppeteer_crawler.js, src/key_value_store.js, src/puppeteer.js, src/puppeteer_pool.js, src/puppeteer_utils.js, website/pages/en/index.js, website/sidebars.json
Fix various links throughout the documentation, mostly fragment identifiers and Puppeteer links.
=> Docs: fix various links

CHANGELOG.md, src/crawlers/cheerio_crawler.js, test/crawlers/cheerio_crawler.test.js
2 Cheerio Scraper users requested this. This is mostly needed when the websites are sending `Content-Type` without charset, which causes `CheerioCrawler` to fall back to `utf8` and that means corrupted results when the encoding is not actually `utf8`
I'll add it to the scraper with next release of SDK.
=> Add option to set response encoding to CheerioCrawler

website/static/css/custom.css
Attempt to make these buttons more readable:
=> Web - attempt to fix text formatting of buttons

src/session_pool/session.js
I was thinking it was a bug in my code, but the `Date` is using the parsed `expires` as seconds instead of milliseconds, making nearly all cookies "expires" as somewhere around `1970-01-xx` (when using `page.cookies()` / `session.setPuppeteerCookies()`). ToughCookie seems to parse `expires` and `maxAge` to unix timestamp seconds and seems correct: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
EDIT: thinking more about this, there should be tests covering the verification of expiry on integration tests
EDIT2: Doesn't cover -1, saw some expires being `1969` instead of `1970`
=> cookie expires uses seconds not milliseconds

src/utils.js
Lambda, to my surprise, does not have the `ps` command and there's no way to get it installed. This change modifies the memory detection logic to:
* Detect if it's running in a lambda environment
* Use a combination of the stated total memory via `AWS_LAMBDA_FUNCTION_MEMORY_SIZE` and the gross memory usage to infer available free memory instead of the `ps` command. 
For anyone who might run into this PR in the future, you'll also need to modify the storage directory in order to avoid a `Error: ENOENT: no such file or directory, mkdir` error when executing on lambda:
```
process.env.APIFY_LOCAL_STORAGE_DIR = '/tmp/apify_storage';
```
=> Support detecting memory usage when running on aws lambda

CHANGELOG.md, src/utils.js
Fix #693 by falling back to system readings. It will probably give bad readings, but it's better than crashing the process with no chance of handling that exception.
It's also the second issue in the last month that targets `getMemoryInfo()`.
=> Fall back when memory cgroups are unavailable

src/utils.js, test/utils.test.js
Fix #699. While doing this I found that the warning is actually printed only when `APIFY_SDK_LATEST_VERSION` is present, which means it's never printed locally and is only printed on platform.
We could prevent adding this env var for public actors to achieve a similar result to this PR.
=> Add option to disable outdated warning

docs/guides/getting_started.md
Hi! I came across this issue while going through the Getting Started guide.
`Apify.getInput()` returned null even though I had an `INPUT.json` file at the specified path. Turns out this is because this path is meant to be snake_case, not kebab-case.
```
INFO  System info {"apifyVersion":"0.20.4","apifyClientVersion":"0.6.0","osType":"Windows_NT","nodeVersion":"v12.12.0"}
```
=> Fix key_value_store path in Getting Started guide

src/request.js, test/crawlers/basic_crawler.test.js, test/events.test.js, test/request.test.js
Getting rid of useless `null`s that cause problems here and there. It's breaking because `null` -> `undefined` is fine, but `null` -> `[]` in `errorMessages` may cause issues.
=> Improve Request property defaults

src/request_queue.js
We tracked a bug we were seeing when crawling a reasonably large site (250K URLs) down to what looks to be a race condition within `RequestQueueLocal`. The bug causes BasicCrawler's `runTaskFunction()` to throw and prematurely terminate the crawl.
Explanation of the race condition (as far as we understand it):
1. `fetchNextRequest()` while loop picks up **queueOrderNo**
2. CheerioCrawler makes request
3. `markRequestHandled()` moves from pending to handled and deletes **queueOrderNo** from in progress
4. `fetchNextRequest()` while loop picks up _same_ **queueOrderNo** (using data from `fs.readdir` before `markRequestHandled()`  moved the file), sees it is not in progress, calls `_getRequestByQueueOrderNo()` which doesn't throw an ENOENT (because `_getRequestByQueueOrderNo()` checks both …
=> RequestQueueLocal race condition

src/constants.js, src/crawlers/cheerio_crawler.js
Improved reference to session pool options to point to cheerio crawler instance in the underlying basic crawler instance. Otherwise changing the options after initializing, or through the `.use()` the method won't work correctly.
=> CheerioCrawler - reference the session pool options to underlying basic crawler

src/proxy_configuration.js
Proxy was always on with default config when used by directly passing the input UI proxy object.
=> Disable proxy when useApifyProxy: false is used in proxy conf

src/utils_request.js, tsconfig.json
* closes #757
PS: JSDoc weirdness of the day: the order of `@property` matters for TS (maybe it's a interoperability bug...). tried with 2 TS versions, they had the same issue. my guess is that having `@apify/http-request` inside property description breaks everything below this line. might have issues somewhere else, I'll check later
created TS issue here https://github.com/microsoft/TypeScript/issues/39976
=> reorder property in JSDoc for RequestAsBrowserOptions

src/proxy_configuration.js, test/proxy_configuration.test.js
When Apify Proxy is unavailable/down, the access check throws. This PR adds retries and reduces the timeout from 30 to 5 secs to prevent too long wait times. If it fails anyway, it will let the process continue and if there are issues with access rights or proxy, they will be handled by the crawlers.
=> Fix proxy check crashes

package.json, src/crawlers/basic_crawler.js, src/crawlers/cheerio_crawler.js, src/crawlers/puppeteer_crawler.js, src/crawlers/statistics.js, src/request_list.js, src/session_pool/session_pool.js, test/crawlers/basic_crawler.test.js, test/crawlers/statistics.test.js, test/request_list.test.js
The internal state are saved as `STATISTICS_STATE_[INDEX]`, which should be, when using just one crawler, `STATISTICS_STATE_[INDEX]`. if the crawlers retain their loading order, each one will have their persisted stats in a separate key. 
`startLogging()` now does a bit more than just actually logging, might be a misnomer. 
about the log, should it inherit from `BasicCrawler` log or be a standalone? decided to leave the `logMessage` as-is.
closes: #656 #177
~there's a caveat to this: when persisting `startedAt`, locally, if the person doesn't use `--purge`,  or when on the platform, aborting the run then resurrecting much later, the `totalMinutes` in `getCurrent()` become completely skewed. if the `startedAt` doesn't get restored upon reading from persisted state, the `perMinute` stats …
=> make statistic class persistable on multiple instances

src/crawlers/puppeteer_crawler.js
Added validation for `persistCookiesPerSession: true` used with no `sessionPool: false`
=> Puppeteer crawler: Added validation for persisting cookies per session with no session pool

src/puppeteer_request_interception.js, test/puppeteer_request_interception.test.js
Changed format of puppeteer request `headers` - now capitalized formatting is used because it is more like real browser headers
=> PuppeteerCrawler: request headers capitalized format

src/request.js, test/request.test.js
Partially fixes #748. There's still a place for improvement. It was ~50ms with `type-check`, increased to ~450ms with `ow`. Now it should be ~100ms.
=> Improve request creation performance

src/utils_request.js
`requestAsBrowser` example added, `@apify/http-request` package name fixed, typo fixed.
Fixes #575
=> add requestAsBrowser example

src/autoscaling/system_status.js
Default maxEventLoopOverloadedRatio set to 0.6; fixed default values in docs. Closes #445.
@mnmkng I don't really need to over-write it for basic crawler specifically and could just update the default `SystemStatus` value in this case, or do I?
=> increase default maxEventLoopOverloadedRatio to 0.6

src/crawlers/browser_crawler.js, test/crawlers/browser_crawler.test.js
We have to set the default only if the sessionPool is on. Otherwise it will throw an error.
=> Fixed default persistCookiesPerSession

src/crawlers/browser_crawler.js, src/crawlers/cheerio_crawler.js, src/session_pool/session.js, test/crawlers/cheerio_crawler.test.js, test/crawlers/puppeteer_crawler.test.js, test/session_pool/session.test.js
For some cookies without an expiration date (session cookies), puppeteer would return `expires: -1` (chrome would show `Expires: Session` for these). Puppeteer methods would work completely fine while saving such cookies to session leads to some inconsistent behavior - either cookie would not be set to a session or it would not be then set to the page.
Fixes #922
=> fix inconsistency between puppeteer and sessionPool cookies, add tests

CHANGELOG.md, package.json, src/actor.js, test/actor.test.js
Fixes #951 (keep `{ contentType, body }` as `Apify.call()` output (instead of `{ key, value, contentType }`, same for `Apify.callTask()`).
=> fix Apify.call() output

docs/guides/getting_started.md
Fixes mainly the selectors, also adds a small note about extracting numbers
from formatted strings with thousands separators.
Also tries to fix right sidebar navigation by removing links from headers.
=> docs: fix examples in the getting started section

docs/guides/typescript_actor.md, src/browser_launchers/playwright_launcher.js, src/browser_launchers/puppeteer_launcher.js, tsconfig.json
* minor update the TS actor guide
LaunchOptions is now available for both Puppeteer and Playwright, making the TS section a bit outdated. this works for TS without the need for having Puppeteer or Playwright installed, having the `@types/` is enough
Node 12.9+ supports all ES2019 language features, so it's the lowest denominator according to this https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
=> add LaunchOptions for both contexts

.github/workflows/check.yml, .github/workflows/release.yml, package.json
I need the bumped version of storage local to build the images without the unnecessary `node-gyp` dependencies, which are not present in the underlying node images. I also added the node 16 to the actions.
=> chore: bump storage-local, node 16

package.json
This is to fix memory info on Windows - see https://github.com/apify/ps-tree/pull/1
=> chore: update `@apify/ps-tree` to 1.1.4

package.json
Also removes `@types/puppeteer` as they are now included in the `puppeteer` package.
Closes #1005
=> chore: define puppeteer and playwright as optional peer dependencies

.github/workflows/release.yml
A [PR in `apify-actor-docker`](https://github.com/apify/apify-actor-docker/pull/57) renames the repository dispatch event for building Node images with the Apify SDK, so this PR changes the name of the event when calling that repository dispatch from here.
Please merge only after that PR is merged, ideally immediately after, so the building of the actor images with Apify SDK is not broken.
=> chore: Rename GitHub workflow event for building node images

CHANGELOG.md, jest.config.js, src/crawlers/basic_crawler.js, src/crawlers/browser_crawler.js, src/crawlers/cheerio_crawler.js, src/crawlers/playwright_crawler.js, src/crawlers/puppeteer_crawler.js, src/utils_request.js, test/crawlers/cheerio_crawler.test.js, test/utils_request.test.js
`CheerioCrawler` downloads the web pages using the `requestAsBrowser` utility function.
As opposed to the browser based crawlers that are automatically encoding the URLs, the
`requestAsBrowser` function will not do so. We either need to manually encode the URLs
via `encodeURI()` function, or set `forceUrlEncoding: true` in the `requestAsBrowserOptions`,
which will automatically encode all the URLs before accessing them.
> We can either use `forceUrlEncoding` or encode manually, but not both - it would
> result in double encoding and therefore lead to invalid URLs.
We can use the `preNavigationHooks` to adjust `requestAsBrowserOptions`:
```
preNavigationHooks: [
(crawlingContext, requestAsBrowserOptions) => {
requestAsBrowserOptions.forceUrlEncoding = true;
}
]
```
Closes #679
Related #658
=> feat: add `forceUrlEncoding` option to `requestAsBrowser`

src/configuration.js, src/storages/key_value_store.js
This should fix the duplicated `/v2` in the client configuration. However, the API version should be configurable in one place, not defined in the kV store string. So another option I have in mind is that the `apify-client` should handle the versions a bit better - When the version part is presented in the URL, the client will validate the version part. If the version exists, it will keep it like that. If the version is not present in the URL, the client would add the default one.
=> fix: configuration apiBaseUrl

CHANGELOG.md, src/constants.js, src/storages/key_value_store.js
context:
> After I upgraded Apify SDK to latest, KeyValue store urls are now giving IP http://10.0.81.159:8010//v2/key-value-stores/ instead of https://api.apify.com/v2/key-value-stores/ which is again not working as public url. Can you please let me know if this is bug or I am doing something wrong ? store.getPublicUrl(key) is how I am composing url
I am on 1.3.1 SDK version
=> fix: hardcode public API URL in key-value store URL getter

.github/workflows/check-ts-support.yml, .github/workflows/check.yml, .github/workflows/release.yml, CHANGELOG.md, package.json, src/crawlers/cheerio_crawler.js, test/crawlers/cheerio_crawler.test.js, test/typescript/crawlers/cheerio_crawler.test.ts
After update to `cheerio@1.0.0-rc.10` the `$.html()` calls started failing with the following error:
```
ERROR CheerioCrawler: Request failed and reached maximum retries {"url":"https://www.example.com/","method":"GET","uniqueKey":"https://www.example.com"}
TypeError: Cannot read property 'charset' of undefined
at Object.exports.getAttrList (/Users/mnmkng/Projects/Apify/Actors/bug-test/node_modules/parse5-htmlparser2-tree-adapter/lib/index.js:283:53)
at Serializer._serializeAttributes (/Users/mnmkng/Projects/Apify/Actors/bug-test/node_modules/parse5/lib/serializer/index.js:99:40)
at Serializer._serializeElement (/Users/mnmkng/Projects/Apify/Actors/bug-test/node_modules/parse5/lib/serializer/index.js:67:14)
at Serializer._serializeChildNodes …
```
=> fix: cheerio issues with HTML serialization

package.json
The `2.1.3-beta` uses `hpagent` which doesn't support usual web proxies.
Some Apify proxies don't support the `CONNECT` protocol as well.
Therefore it was returning `socket hang up` errors.
Unfortunately this brings back unhandled exceptions caused by `agent-base` / `http-proxy-agent`.
=> Pin `got-scraping` to `2.1.3`

src/crawlers/browser_crawler.js, src/crawlers/cheerio_crawler.js, src/proxy_configuration.js
Not sure how do I test this. Another question: Does `ProxyConfiguration` always get set up before setting up a browser? If no, then we should fix this so this option gets applied as well.
=> Disable SSL validation on MITM proxies

package.json, src/browser_launchers/browser_launcher.js, src/browser_launchers/puppeteer_launcher.js, test/browser_launchers/playwright_launcher.test.js, test/browser_launchers/puppeteer_launcher.test.js
=> fix: incognito pages and user data dir

tools/typescript_fixes.js
This should suppress most of the TS build errors caused by missing peer dependencies,
while still keeping things working when the dependency is installed.
=> fix: add ts-ignore comments to imports of optional peer dependencies

src/apify.js, src/session_pool/session_pool.js, src/storages/dataset.js, src/storages/key_value_store.js, test/apify.test.js
The instance level config was ignored in this method, as well as in
openKeyValueStore. Both now allow passing the config object in second
parameter, and will respect the current config when used from the SDK
instance.
Related: #956
=> fix: use config instance in `sdk.openSessionPool()`

src/utils_social.js, test/utils_social.test.js
The `.*` in the regexp caused everything in between two youtube urls to be matched as the url, resulting in issues when there were more than one youtube url. 
Closes #881
=> fix: fix `YOUTUBE_REGEX_STRING` being too greedy

src/proxy_configuration.js
=> feat: warn if apify proxy is used in proxyUrls

src/puppeteer_utils.js
This should close #1010 (but I don't know if this is the API you referred to in your issue, and it's the only other relevant example I found for scrolling). There's still a bug I need to find out why it breaks (for some reason the test case for `waitForSecs: Infinity, scrollCancelCallback` throws..)
=> feat(InfiniteScroll): use puppeteer emulating scrolls instead of window.scrollBy

src/utils_social.js, test/utils_social.test.js
Closes #526 
One issue I found is that there seem to be channels on YouTube that work at the root level (https://www.youtube.com/jacksepticeye, https://www.youtube.com/pewdiepie are some that I found, and it seems that YouTube has redirects in place for all named channels (? citation needed)) so I don't exactly know how we should handle these. Thoughts @metalwarrior665?
=> feat: support channel and user links in YouTube regex

src/utils_request.js, test/utils_request.test.js
=> fix: incorrect offset in `fixUrl` function

src/session_pool/session_pool.js
Closes #752 
Might need to change the documentation string, right now it's a 1:1 copy from KV
=> feat(SessionPool): allow passing `forceCloud` down to the KV store

src/utils_request.js, test/utils_request.test.js
Fixes https://github.com/apify/apify-js/issues/1193
=> fix: use encodeURIComponent instead of encodeURI

src/crawlers/basic_crawler.js
A step of #1100, retrying (adding back to the queue) is not possible since we don't know at which point it's failing. Could be fetching the next request.
=> fix: add timeout for task function

package.json, src/crawlers/basic_crawler.js
This adds 30s timeouts with 3 retries to the async places inside
`runTaskFunction` that might be causing the zero concurrency bug.
We now get a warning every time such place timeouts and a hard
failure after 3 retries.
Related: #997
=> fix: add timeouts with retries to `runTaskFunction()`

src/storages/request_queue.js
This should help with following problem:
=> fix: do not use `tryCancel()` from inside sync callback

CHANGELOG.md, src/puppeteer_utils.js
Should address following issue:
=> fix: wait when `body` is not available in `infiniteScroll()` from Puppeteer utils

CHANGELOG.md, src/utils_log.js, test/utils.test.js
=> fix: expose logger classes on the `utils.log` instance

CHANGELOG.md, src/crawlers/cheerio_crawler.js, test/crawlers/cheerio_crawler.test.js
When changing the headers in cheerio crawler, first request may have failed as
headers object was not set. Now it will be always there before we try to access it.
=> fix: ensure `request.headers` is set

src/crawlers/crawler_utils.js
This issue https://github.com/apify/apify-js/issues/1266 is kinda solved in the latest beta, but while testing I stuck upon an edge case when you try to set only one cookie (like mentioned in the issue), which leads to `cookies` array here having an actual cookie and a second item, which is gonna be an empty string, which is leading to:
```
TypeError: Cannot read properties of undefined (reading 'key')
at /Users/AndreyBykov/Documents/Apify/Playground/playground/node_modules/apify/build/crawlers/crawler_utils.js:52:31
at Array.find (<anonymous>)
at mergeCookies (/Users/AndreyBykov/Documents/Apify/Playground/playground/node_modules/apify/build/crawlers/crawler_utils.js:51:62)
at CheerioCrawler._mergeRequestCookieDiff (/Users/AndreyBykov/Documents/Apify/Playground/playground/node_modules/apif …
```
=> fix: cookies setting in preNavigationHooks

src/utils.js
Reupload: Corrected conventions on naming conventions
A PR for the case where the user windows OS is in a different language and the 'Typical Chrome Executable Path' is on a 'non-English-standard' ProgramFiles folder.
In windows, it can be gotten by the environment variable ProgramFiles(x86).
=> fix: improve guessing of chrome executable path on windows

package.json
For now, this is blocked while I await an answer for https://github.com/puppeteer/puppeteer/issues/8059
All tests seem to pass fine with v13 (except the userDataDir one [EDIT from the future: see issue above, which was fixed and published]), and the docker image does build (locally you'll need to change all npm installs to include --force to ignore the peer dep errors if you want to try them)
=> feat: bump puppeteer support to up to v13.x

src/enqueue_links/click_elements.js, test/enqueue_links/click_elements.test.js
Here is the feature i was trying to introduce as mentioned in #1294.
It adds the option for multiple clicks.
Use cases:
- A normal use would be for example to handle [dblclick events](https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event). They have been introduced for many years and have high compatibility with most browsers.
- In my personal use case, i was considering supporting some existing "application like" web interactions for an utility app aiming at organizing and managing some private files in the cloud.
I only added tests for dblclick events (coping the existing ones). I think they should apply for most of the situations. But one probably should consider adding some kind of "limited" tests for more dynamic click counts or simply limiting the feature to a …
=> feat: add multiple click

src/apify.js, src/configuration.js
Using `asyncLocalStorage`, `Configuration.getGlobalConfig()` now returns instance-scoped configuration (`sdk.config`).
fixes #1305
=> feat: instance-scoped "global" configuration

src/request_list.js, src/utils.js, test/request_list.test.js
closes #1073
Intended use:
```javascript
const proxyConfiguration = await Apify.createProxyConfiguration({ 
// the proxy is to be specified here 
});
const requestList = await Apify.openRequestList('test',[
{ requestsFromUrl:'http://sitemap.txt/sitemap.txt' }
], { proxyConfiguration }
);
```
=> feat: requestList accepts proxyConfiguration for `requestsFromUrls`

CHANGELOG.md, package.json, src/crawlers/basic_crawler.js, src/storages/request_queue.js, test/request_queue_reset.test-e2e.js
We now track last activity done on a `RequestQueue` instance:
- added new request
- started processing a request (added to `inProgress` cache)
- marked request as handled
- reclaimed request
If we don't detect one of those actions in last 5 minutes, and we have some requests in the `inProgress` cache, we try to reset the state. We can override this limit via `APIFY_INTERNAL_TIMEOUT` env var. If request handler timeout value is higher, we use that instead. This internal timeout is also used when executing the user-provided request handler, so we know there needs to be some activity in this internal (the handler either finished or timeouted).
This should finally resolve the 0 concurrency bug, as it was always about stuck requests in the `inProgress` cache.
Closes #997
=> fix: reset `RequestQueue` state after 5 minutes of inactivity

package.json, src/storages/key_value_store.js, test/storages/key_value_store.test.js
Right now the only way for a stream to be save in a KV store is using a buffer but (correct me if I'm wrong), that would mean using the memory (while passing the stream would directly send it via the network to the s3 bucket).
Current working solution:
```js
async function concatStreamToBuffer(stream) {
return new Promise((resolve, reject) => {
const chunks = [];
stream
.on('data', (chunk) => {
chunks.push(chunk);
})
.on('error', (e) => reject(e))
.on('end', () => {
const buffer = Buffer.concat(chunks);
return resolve(buffer);
});
});
}
Apify.main(async () => {
const store = await Apify.openKeyValueStore();
const videoStream = new Stream();
// ...
const videoBuffer = await concatStreamToBuffer(videoStream);
await store.setValue('video', videoBuffer, { contentType: 'video/mp4' });
});
``` …
=> feat: allow passing a stream to `KeyValueStore.setRecord`

src/browser_launchers/puppeteer_launcher.js
Based on the changes in apify/apify-js@7d20ac2, I would expect the URL follow the other files.
=> docs: url mismatch

CHANGELOG.md, src/playwright_utils.js, src/puppeteer_utils.js, test/playwright_utils.test.js, test/puppeteer_utils.test.js
closes #1336
JQuery requires the global `document` object, which is not available when `Page.addInitScript`-s are added. This solution, therefore, introduces the new `injectFile` option `waitForDOM`, which ensures the script does not get injected until the DOM load.
The implementation of `waitForDOM` needs rework. Loading bigger scripts (as JQuery, for instance) takes a longer time and introduces "race condition," as there is no way of waiting for the script load to finish. This makes testing + usage a guessing game.
=> feat: add `playwright.utils.injectJQuery`

src/crawlers/basic_crawler.js
When using `RequestList`, the `request.id` is not there so we use the `uniqueKey` to track the `request`, but to fail it, we used the `url`.
=> fix: ensure failed req count is correct when using `RequestList`

CHANGELOG.md, src/browser_launchers/puppeteer_launcher.js
This should fix the random failure of actor runs using puppeteer crawler in headful mode. It first appeared in SDK 2.3.0 after updating puppeteer to version 13.
Seems like the issue appeared in puppeteer [a long time](https://github.com/puppeteer/puppeteer/issues/3309) ago, and is still [not fixed](https://github.com/puppeteer/puppeteer/issues/7050). The last puppeteer version working without this issue is 10.4.0. My bet is it's related to OOP iframes changes in [v11](https://github.com/puppeteer/puppeteer/releases/tag/v11.0.0). The issue is pretty random though and hard to reproduce. Sometimes it happens after 1-2 requests are processed, sometimes after 10-15 minutes run, sometimes run could finish successfully. Adding `--disable-site-isolation-trials` flag fixes it.
No need to add this …
=> fix: random puppeteer crawler (running in headful mode) failure

CHANGELOG.md, package.json, src/browser_launchers/playwright_launcher.js, src/constants.js, test/crawlers/playwright_crawler.test.js, test/crawlers/puppeteer_crawler.test.js
Uses predefined UA instead of the default "headless" ones.
=> fix: use default user agent for playwright with chrome

CHANGELOG.md, src/enqueue_links/enqueue_links.js, test/enqueue_links/enqueue_links.test.js
Previously if using the cheerio crawler, the enqueue_links function would error if any href contained a URL that was invalid.
Updated the `extractUrlsFromCheerio` function to gracefully handle invalid relative and absolute URLs. Logging a warning message if an invalid URL is encountered.
Closes #1368
=> fix: update utils.enqueueLinks to ignore invalid URLs when using cheerio

packages/cheerio-crawler/src/internals/cheerio-crawler.ts, test/core/crawlers/cheerio_crawler.test.ts
The type arg is still available in the `CheerioCrawlingContext` but having one for the whole crawler does not make much sense and can be confusing.
=> fix: remove `JSONData` generic type arg from `CheerioCrawler`

packages/basic-crawler/src/internals/basic-crawler.ts, packages/cheerio-crawler/src/internals/cheerio-crawler.ts, test/core/crawlers/basic_crawler.test.ts
+ `CheerioFailedRequestHandler` to `CheerioErrorHandler`
=> fix: rename interface `FailedRequestHandler` to `ErrorHandler`

packages/browser-crawler/src/internals/browser-crawler.ts
It's just a shortcut for `launchContext: { launchOptions: { headless } }`.
=> fix: add `headless` option to `BrowserCrawlerOptions`

packages/browser-crawler/src/internals/browser-crawler.ts, packages/cheerio-crawler/src/internals/cheerio-crawler.ts, packages/core/src/enqueue_links/enqueue_links.ts
Now it's correctly resolving the baseUrl used in the filtering in `enqueueLinks`
while also resolving all relative links to the loaded url of the request
=> fix: enqueue link not finding relative links if the checked page is redirected

packages/playwright-crawler/package.json, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/package.json, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts, test/core/playwright_utils.test.ts, test/core/puppeteer_utils.test.ts
add the respective options for both utils and for context utils.
add the tests.
also fixed pptr links in utils
=> feat: add parseWithCheerio for puppeteer & playwright

packages/memory-storage/src/workers/instance.ts
For now the files are saved in the same process as the memory storage instance
=> chore: disable worker for memory storage

packages/core/src/constants.ts, packages/core/src/index.ts, packages/core/src/session_pool/session.ts, packages/core/src/session_pool/session_pool.ts, test/core/crawlers/basic_crawler.test.ts, test/core/crawlers/browser_crawler.test.ts, test/core/crawlers/cheerio_crawler.test.ts, test/core/session_pool/session.test.ts, test/core/session_pool/session_pool.test.ts
=> feat: allow configuring what status codes will cause session retirement

docs/guides/apify_platform.mdx
- last `our` -> `your`
- Actor shortcuts - removed 1 from code snippet, but kept in `storages` section - explained on Slack why (we could remove it if you really think it's not necessary)
- Added note about running Crawlee on platfrom and actor init
- getPublicUrl
- CRAWLEE_STORAGE_DIR - it feels like a valid point that you could keep this var for local override, but still use the platfrom storages (same way as it was before with APIFY_LOCAL_STORAGE_DIR).
- APIFY/CRAWLEE env vars.
Also adding a screenshot so that you could have a look this time before merging, as there are quite a few changes.
=> docs: more updates to apify_platform guide

packages/core/src/router.ts, test/core/router.test.ts
```ts
crawler.router.use((ctx) => { ... });
```
=> feat: add support for middlewares to the `Router` via `use` method

packages/cheerio-crawler/src/internals/cheerio-crawler.ts
Somehow it's missing in `CheerioCrawler` 🤷‍♂️
=> fix: add missing configuration to CheerioCrawler constructor

packages/playwright-crawler/src/internals/utils/playwright-utils.ts, test/core/playwright_utils.test.ts
=> feat: add `utils.playwright.blockRequests()`

packages/core/src/storages/key_value_store.ts
=> feat: prefer `/INPUT.json` files for `KeyValueStore.getInput()`

packages/basic-crawler/src/internals/basic-crawler.ts, packages/core/src/errors.ts, test/core/crawlers/browser_crawler.test.ts, test/core/crawlers/cheerio_crawler.test.ts, test/core/crawlers/puppeteer_crawler.test.ts
The PR adds the error to the crawling context for the error handlers.
Since you can throw *anything*, the correct type for errors in the error handlers is unknown instead of `Error`, so this PR fixes that too.
=> feat: add `RetryRequestError` + add error to the context for BC

packages/basic-crawler/src/internals/basic-crawler.ts, test/core/crawlers/basic_crawler.test.ts
Allows to keep the crawler running even when the queue is empty. Use `crawler.teardown()` to stop it.
Closes #1436
=> feat: add `keepAlive` to crawler options

README.md
As mentioned in [the Hacker News announcement thread](https://news.ycombinator.com/item?id=32568318), several people dislike the definite article when referring to tech products. Would it be possible to change the README.md and the "About" section?
Thanks!
=> docs: Say "a X" instead of "the X" in README.md

packages/core/src/events/event_manager.ts, test/e2e/automatic-persist-value/actor/.gitignore, test/e2e/automatic-persist-value/actor/Dockerfile, test/e2e/automatic-persist-value/actor/apify.json, test/e2e/automatic-persist-value/actor/main.js, test/e2e/automatic-persist-value/actor/package.json, test/e2e/automatic-persist-value/test.mjs, test/e2e/tools.mjs
Should resolve #1463 by ensuring the persist state listeners are executed when events.close is called
For the actor users, we also need https://github.com/apify/apify-sdk-js/pull/49
=> fix: wait for persist state listeners to run when event manager closes

packages/playwright-crawler/src/internals/playwright-crawler.ts
The `page` variable was missing, so I added it. 😉
=> docs: add a variable in the example code

packages/core/src/request.ts
The docs say, "This behavior applies to all Apify SDK classes..." but I believe you are referring to Crawlee.
=> docs: replace "Apify SDK" with "Crawlee"

packages/puppeteer-crawler/src/internals/enqueue-links/click-elements.ts
👋 Crawlee team!
I'm currently developing on top of Crawlee, and have been leveraging `enqueueLinksByClickingElements` to navigate links that require the preservation of session data. There are thousands of links, so moving these page contexts into the request queue under a new label is preferred. I am currently seeing an issue with enqueueing new work with custom labels. 
```
Reclaiming failed request back to the list or queue. Did not expect property `label` to exist
```
A fix below, which ensures the validation of `label` in `RequestOptions` enables `enqueueLinksByClickingElements` to queue up new links under a custom label.
=> fix: allow `label` in `enqueueLinksByClickingElements` options

packages/http-crawler/src/internals/http-crawler.ts, test/core/crawlers/http_crawler.test.ts
Fixes https://github.com/apify/crawlee/issues/1267
~I'd prefer if we used `cookieJar` instead, because the headers should be treated case-insensitively (according to the spec) and as of now `options.headers` is just a plain object, meaning `cookie` and `Cookie` and `COOKIE` are treated as separate properties. Node.js will select the last header case-insensitively. Response headers are lowercased by default, it's just a matter of how to handle request cookie headers.~ rather unavoidable
=> fix: handle redirect cookies

package-lock.json, packages/core/src/enqueue_links/shared.ts, packages/puppeteer-crawler/package.json, scripts/typescript_fixes.mjs
Fixes the devtools-protocol typing issue (should we be setting it as a dependency or letting it come from puppeteer? I think the latter is fine), as well as the broken type in /core for filteringRequestsWithPatterns (typescript inlined it to import from our mapped paths)
=> fix: correct some typing exports

packages/basic-crawler/src/internals/basic-crawler.ts, packages/utils/src/internals/error_tracker.ts
It now prints something like this:
```
INFO  CheerioCrawler: Error analysis: {"totalErrors":1,"uniqueErrors":1,"mostCommonErrors":["1x: 502 - Internal Server Error: (/home/szm/Desktop/crawlee/packages/http-crawler/dist/internals/http-crawler.js:412:19)"]}
```
Also fixed the order so it prints actually most common errors first.
=> refactor: error analysis message

packages/core/src/configuration.ts, packages/memory-storage/src/memory-storage.ts, packages/memory-storage/src/resource-clients/dataset-collection.ts, packages/memory-storage/src/resource-clients/dataset.ts, packages/memory-storage/src/resource-clients/key-value-store-collection.ts, packages/memory-storage/src/resource-clients/key-value-store.ts, packages/memory-storage/src/resource-clients/request-queue-collection.ts, packages/memory-storage/src/resource-clients/request-queue.ts, packages/memory-storage/src/utils.ts, packages/memory-storage/src/workers/worker-utils.ts, packages/memory-storage/test/__shared__.ts, packages/memory-storage/test/no-writing-to-disk.test.ts, packages/memory-storage/test/write-metadata.test.ts
Resolves the request in https://github.com/apify/crawlee/discussions/1533
=> feat: allow disabling storage persistence

package-lock.json, packages/basic-crawler/src/internals/basic-crawler.ts, test/core/crawlers/basic_crawler.test.ts
See this Discord post to fully understand the use case: https://discord.com/channels/801163717915574323/1019936393235017769
Didn't want to make big changes to existing code so kept the else statement and, therefore,the code repeats itself a little.  If a refactor is in order, I can easily fix.
=> fix(basic-crawler): handle `request.noRetry` after `errorHandler`

packages/basic-crawler/src/internals/basic-crawler.ts, packages/browser-crawler/src/internals/browser-crawler.ts, packages/cheerio-crawler/src/internals/cheerio-crawler.ts, packages/core/src/autoscaling/system_status.ts, packages/core/src/crawlers/crawler_commons.ts, packages/core/src/enqueue_links/enqueue_links.ts, packages/http-crawler/src/internals/http-crawler.ts, packages/jsdom-crawler/src/internals/jsdom-crawler.ts, packages/playwright-crawler/src/internals/playwright-crawler.ts, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/src/internals/puppeteer-crawler.ts, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts, test/core/crawlers/browser_crawler.test.ts, test/core/crawlers/puppeteer_crawler.test.ts
- simplifies `enqueueLinks` implementation - no more child types for options
- improves types of context properties, e.g. `crawler` has correct type in browser crawlers
- adds jsdoc for context helpers, e.g. `injectJQuery` or `sendRequest`
- all context helpers have their "jsdoc copy", we could mauybe use `@inheritDoc` as an inline tag pointing to the implementation, but that would mean taking the same jsdoc - here we instead have customized version, that dont have the `page` param (as its context bound) and have context related examples
- contains unrelated changes in the `SystemStatus` to support edge case i found, we can move this outside of the PR but its not really worth having a changelog line on its own :]
=> docs: refactor crawling context helper methods to have them properly documented

package.json, packages/basic-crawler/test/migration.test.ts, packages/browser-crawler/test/migration.test.ts, packages/cheerio-crawler/test/migration.test.ts, test/core/storages/key_value_store.test.ts
Possible explanation: sme tests were not using the storage emulator, and the automatic purge of default storage sometimes collided with another test.
We might want to consider disabling the file system persistence in the storage emulator, could result in perf improvements of the tests.
=> test: fix flakyness of some test that used default storage

packages/core/src/storages/dataset.ts, packages/core/src/storages/key_value_store.ts, packages/core/src/storages/request_queue.ts
This allows us to extend the classes (like we do in SDK) while not requireing us to extend the static `open` method
=> fix: build storage classes by using `this` instead of the class

packages/playwright-crawler/src/internals/utils/playwright-utils.ts
This prevents many unwanted artefacts in screenshots.
=> feat(playwright): disable animations when taking screenshots

packages/basic-crawler/src/internals/basic-crawler.ts, test/e2e/migration/actor/.gitignore, test/e2e/migration/actor/Dockerfile, test/e2e/migration/actor/apify.json, test/e2e/migration/actor/main.js, test/e2e/migration/actor/package.json, test/e2e/migration/test.mjs
1. I noticed that `_pauseOnMigration` does not stop the autoscaled pool, keeping the event loop alive. Is this expected?
Google Meet summary: probably, let's consult with Ondra
Resolution: it should probably not block the event loop, but there's bunch of other things that are blocking the event loop, such as snapshotter so probably not worth the change
3. Do we want to E2E test this? Done ✅ 
Flaky tests encountered (should be a separate issue?):
```
https://github.com/apify/crawlee/actions/runs/3218900877/jobs/5263614933#step:9:70
FAIL test/core/session_pool/session_pool.test.ts (8.869 s)
● SessionPool - testing session pool › should initialize with default values for first time
ENOENT: no such file or directory, stat '/home/runner/work/crawlee/crawlee/storage/datasets/default/000000001.js …
```
=> feat: enable migration testing

packages/basic-crawler/src/internals/basic-crawler.ts
The session used in a request handler that throws an error is now **marked bad**. 
This is in line with no-error behavior marking the session as good - but might cause (unwanted) faster session rotation.
closes #1635 
closes #1648
=> fix: mark session as bad on failed requests

packages/basic-crawler/src/internals/basic-crawler.ts, test/core/crawlers/basic_crawler.test.ts
=> fix: concurrency option override order

packages/utils/src/internals/error_tracker.ts, packages/utils/test/non-error-objects-working.test.ts
=> fix: handle non-error objects thrown gracefully

packages/core/package.json
Needed for https://github.com/apify/apify-sdk-js/pull/122 (and somehow the only one missing)
=> chore: re-export package.json from the core module

packages/browser-crawler/src/internals/browser-launcher.ts
The launcher property should have a description to make it more understandable in the documentation.
=> docs: add launcher description

packages/basic-crawler/src/internals/basic-crawler.ts, packages/browser-crawler/src/internals/browser-crawler.ts, packages/core/src/request.ts, packages/http-crawler/src/internals/http-crawler.ts, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts, test/core/crawlers/basic_crawler.test.ts, test/core/crawlers/browser_crawler.test.ts
Let's play Bug Fix or a Breaking Change!
Because `requestHandler` and `pre/postNavigationHooks` share the same context, the `surviveNavigations` is disabled for `injectJQuery` in all of those handlers/hooks.
Consider the following snippet:
```ts
{
preNavigationHooks: [
async ({ injectJQuery }) => injectJQuery();
],
requestHandler: async ({ page })  => {
await page.evaluate(() => $('title').text);
},
}
```
This could have worked before (albeit it was very unstable), but will fail every time now.
What is it then? _Bug Fix or a Breaking Change?_
=> fix: injectJQuery in context does not survive navs

docs/examples/jsdom_crawler.mdx, docs/examples/jsdom_crawler.ts, package-lock.json, packages/browser-pool/src/abstract-classes/browser-plugin.ts, packages/jsdom-crawler/package.json, packages/jsdom-crawler/src/internals/jsdom-crawler.ts, test/e2e/jsdom-react-ts/actor/.gitignore, test/e2e/jsdom-react-ts/actor/Dockerfile, test/e2e/jsdom-react-ts/actor/apify.json, test/e2e/jsdom-react-ts/actor/main.ts, test/e2e/jsdom-react-ts/actor/package.json, test/e2e/jsdom-react-ts/actor/tsconfig.json, test/e2e/jsdom-react-ts/test.mjs
What's missing here is session integration. For now every page load has a different `cookieJar`.
https://github.com/jsdom/jsdom#advanced-configuration Resources such as CSS / JS can be downloaded via a proxy (this should be optional, as downloading several megabytes through a proxy sometimes takes too long). Also the user-agent is `jsdom/xxx` for downloading resources, which should be changed.
The proposals above probably require a bigger change in Session API (should be a separate PR), e.g. the generated headers should be stored in the session, not in `got-scraping`, otherwise we don't know what user agent we should pass to JSDOM. Also I don't see any reason why the Session API does not expose `cookieJar` directly.
=> feat(jsdom-crawler): add runScripts option

packages/core/src/router.ts, test/core/crawlers/cheerio_crawler.test.ts
Trying to improve the error message a bit. I had a situation where I forgot to add a label to `enqueueLinks`. The original message told me that I needed to add a default route, but it did not mention that it's telling me this, because the label was undefined. The issue wasn't a missing default route, but a missing label. Hopefully this one is a bit more clear, but happy to hear other suggestions.
=> fix: make router error message more helpful for undefined routes

.github/workflows/release.yml, .github/workflows/test-ci.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
I found this while looking into fixing changelog generation for our CD pipeline
=> chore: move from set-output to writing to GITHUB_OUTPUT

.github/workflows/release.yml
We might not need to remove the changelog file at all, we'd need to test it out first 👀. If the next release has a broken changelog, we just nuke it for the next release, otherwise we celebrate
=> chore(ci): fix lerna issues with publishing releases

packages/jsdom-crawler/src/internals/jsdom-crawler.ts
Brings `JSDOMCrawler`'s logs closer to `Playwright`/`PuppeteerCrawler` - when set to `true`, the `hideInternalConsole` toggle turns off the JSDOM's calls to `console.log`, hiding the "page" script execution from the user.
=> feat: hideInternalConsole in JSDOMCrawler

packages/core/src/enqueue_links/shared.ts, packages/core/test/enqueue_links/userData.test.ts
=> fix: clone `request.userData` when creating new request object

packages/playwright-crawler/src/internals/enqueue-links/click-elements.ts, packages/puppeteer-crawler/src/internals/enqueue-links/click-elements.ts
It is included in the Options type, but was missing in the ow validation.
Does this need tests @B4nan ?
Fixes #1617
=> fix: allow `userData` option in `enqueueLinksByClickingElements`

package.json
This will help volta users get the correct yarn version (till volta supports `packageManager`)
=> chore: pin node and yarn for volta users

packages/memory-storage/src/resource-clients/request-queue.ts
Logic in https://github.com/apify/crawlee/blob/master/packages/memory-storage/src/resource-clients/request-queue.ts#L291-L298 is wrong. You can even see that `pendingRequestCount` is being changed by `handledCountAdjustment`. There are a few more cases...
I fixed them and also simplified the code to be actually readable
=> fix: Correctly compute `pendingRequestCount` in request queue

packages/memory-storage/src/cache-helpers.ts, packages/memory-storage/src/fs/common.ts, packages/memory-storage/src/fs/dataset/fs.ts, packages/memory-storage/src/fs/dataset/index.ts, packages/memory-storage/src/fs/dataset/memory.ts, packages/memory-storage/src/fs/key-value-store/fs.ts, packages/memory-storage/src/fs/key-value-store/index.ts, packages/memory-storage/src/fs/key-value-store/memory.ts, packages/memory-storage/src/fs/request-queue/fs.ts, packages/memory-storage/src/fs/request-queue/index.ts, packages/memory-storage/src/fs/request-queue/memory.ts, packages/memory-storage/src/resource-clients/dataset.ts, packages/memory-storage/src/resource-clients/key-value-store.ts, packages/memory-storage/src/resource-clients/request-queue.ts, packages/memory-storage/src/utils.ts, packages/memory-storage/src/workers/worker-utils.ts, packages/types/src/storages.ts
This *should* just work and have no issues. Effectively
- if `persistStorage` is enabled, we don't store the data in memory as well as on disk anymore, but rather fetch it on demand from disk
- otherwise, it is kept in memory
This does come with a caveat: when a store of any kind gets loaded and interpreted from disk, even if persistStorage is set to false, the existing entries will act as file system entries. This means a KVS with an INPUT.json will still load from fs when requested and will not be available in RAM.
=> feat(MemoryStorage): read from fs if persistStorage is enabled, ram only otherwise

packages/browser-pool/src/browser-pool.ts, packages/browser-pool/src/fingerprinting/types.ts
Makes the docs for the fingerprinting options in Crawlee a bit more comprehensive.
fixes #1774
=> docs: better docs for fingerprint options

docs/guides/typescript_project.mdx
Typescript project setup guide includes installing `@types/node` package as a step but the dependency was missing in final `package.json`
=> docs: add missing dependency to typescript guide package.json

CONTRIBUTING.md, packages/memory-storage/package.json, yarn.lock
As far as I can tell, `@crawlee/memory-storage` does not use `@crawlee/utils` anywhere, so the dependency was extra.
This will help us a lot with the dependency size in the Apify CLI, which depends on `@crawlee/memory-storage` - this change will remove ~10 MB of dependencies.
=> chore(MemoryStorage): remove extra `@crawlee/utils` dependency

packages/browser-crawler/src/internals/browser-crawler.ts, packages/cheerio-crawler/src/internals/cheerio-crawler.ts, packages/core/src/enqueue_links/shared.ts, packages/jsdom-crawler/src/internals/jsdom-crawler.ts, test/core/enqueue_links/enqueue_links.test.ts
Fixes: https://github.com/apify/crawlee/issues/1802
=> fix: ignore invalid URLs in `enqueueLinks` in browser crawlers

.github/workflows/check-pr-title.yml, packages/core/src/enqueue_links/enqueue_links.ts, packages/core/src/enqueue_links/shared.ts, packages/core/test/enqueue_links/user-provided-patterns-with-enqueue-strategy.test.ts, test/core/enqueue_links/enqueue_links.test.ts
This is a PR to implement the functionality described in #1785. Closes #1785.
=> feat(core): add `exclude` option to `enqueueLinks`

website/src/css/custom.css
Realigns all the docs pages back to the center. Also hides the title next to the logo on scroll.
=> docs: fix main-wrapper alignment on desktop

docs/guides/avoid_blocking_playwright.ts, docs/guides/avoid_blocking_puppeteer.ts, website/versioned_docs/version-3.0/guides/avoid_blocking_playwright.ts, website/versioned_docs/version-3.0/guides/avoid_blocking_puppeteer.ts, website/versioned_docs/version-3.1/guides/avoid_blocking_playwright.ts, website/versioned_docs/version-3.1/guides/avoid_blocking_puppeteer.ts, website/versioned_docs/version-3.2/guides/avoid_blocking_playwright.ts, website/versioned_docs/version-3.2/guides/avoid_blocking_puppeteer.ts, website/versioned_docs/version-3.3/guides/avoid_blocking_playwright.ts, website/versioned_docs/version-3.3/guides/avoid_blocking_puppeteer.ts
Using string literals in the `FingerprintGeneratorOptions` causes TS errors. This PR updates the docs so the examples are in line with the best practices.
Fixes #1813
=> docs: use enums in the fingerprint examples

packages/core/src/storages/request_queue.ts
When we were facing the RQ stuck issues, the solution was to automatically unstuck it in case we detect nothing was happening for ~5 minutes and there are some requests in progress.
This PR removes the condition for in-progress requests, as the queue could get stuck without any in-progress requests too apparently.
https://apifier.slack.com/archives/C0L33UM7Z/p1679262267148309
=> fix: try to detect stuck request queue and fix its state

packages/basic-crawler/src/internals/basic-crawler.ts
If `requestQueue` / `requestList` are uninitialized, the status message contains `undefined` - this PR removes this, no total is shown in this case.
=> fix: status message - total requests

packages/memory-storage/src/resource-clients/key-value-store.ts, packages/memory-storage/src/utils.ts, packages/memory-storage/test/key-value-store-stream.test.ts
Fixes an internally reported bug that caused streams provided to never be read and drained
This also corrects the validator for the value, and removes the other redundant checks that happen when validating an object (called constraints, which are extra validators on top of simple typeof checks) (this is also a feature request for shapeshift!). This might actually (finally) solve #1843 but testing needs to be done
=> fix(MemoryStorage): handling of readable streams for key-value stores when setting records

packages/memory-storage/src/fs/request-queue/fs.ts, packages/memory-storage/src/resource-clients/request-queue.ts
This is added because request queues tend to have a _lot_ of activity on one entry, until the request is finished. This should ensure that no more invalid JSON errors are thrown, while also keeping the memory footprint low once a request entry is no longer accessed (+re-loading from fs if that happens)
=> fix(MemoryStorage): cache requests in `RequestQueue`

packages/core/src/storages/dataset.ts, packages/core/src/storages/key_value_store.ts, packages/core/src/storages/request_queue.ts, packages/core/src/storages/storage_manager.ts, packages/core/src/storages/utils.ts, packages/core/test/storages/open-storage-with-different-client-should-be-respected.test.ts
This is an advanced option that most users will probably never use, however, it will allow you to do the following now:
```ts
import { Actor, Dataset, RequestQueue } from 'apify';
import { MemoryStorage } from '@crawlee/memory-storage';
const memoryStorage = new MemoryStorage({ persistStorage: false, writeMetadata: false });
await Actor.init();
// In the cloud
const dataset = await Dataset.open();
// In memory!!
const rq = await RequestQueue.open(null, { storageClient: memoryStorage });
```
Available on all storages, so if you may need a temporary kvs for instance, now you can have that too
=> feat: support alternate storage clients when opening storages

packages/playwright-crawler/src/internals/utils/playwright-utils.ts
Example for `blockRequests` (https://crawlee.dev/api/playwright-crawler/interface/PlaywrightCrawlingContext#blockRequests) has a couple syntax errors.
=> docs: minor syntax errors in blockRequests docs example

.github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/test-ci.yml, .github/workflows/test-e2e.yml
We want to centralize the secrets used in GitHub workflows to be synced from Doppler. This updates the secrets to those in the organization secrets, and the `APIFY_TOKEN` used in the end-to-end tests to the one synced from Doppler.
=> chore: update GitHub workflow secrets

packages/memory-storage/src/memory-storage.ts
I am _shocked_ this hasn't had issues before but I guess Docker can be finicky as heck.
This has been tested via a report from Discord (https://canary.discord.com/channels/801163717915574323/1109139745470169168) via repo https://github.com/RDzhalmukhamedov/docker-crawlee-test (by doing the changes in the node_modules folder and removing the npm i so it copies in the local node_modules [pps. don't do this at all in your local images.])
=> fix(MemoryStorage): handle EXDEV errors when purging storages

packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts, test/core/playwright_utils.test.ts, test/core/puppeteer_utils.test.ts
Adds the `maxScrollHeight` parameter for the `infiniteScroll` helper functions to stop scrolling when a certain scroll distance has been reached.
=> feat: infiniteScroll has maxScrollHeight limit

test/e2e/linkedom-default-ts/actor/main.ts
Looks like `linkedom` will allow only one read of the page title and resets it to empty string.
```ts
console.log(document.title); // this will print the correct value
console.log(document.title); // while this will return an empty string...
```
=> test: fix assertion in the failing linkedom e2e test

packages/core/src/request.ts, packages/http-crawler/src/internals/http-crawler.ts, test/core/crawlers/cheerio_crawler.test.ts
=> fix(http-crawler): replace `IncomingMessage` with `PlainResponse` for context's `response`

packages/basic-crawler/src/internals/basic-crawler.ts, packages/core/src/storages/request_queue.ts
Previously, the `BasicCrawler.addRequests()` was the only place where we're handling adding the requests in non-blocking manner. This logic is now moved to the `RequestQueue.addRequestsBatched()` method.
This method now also correctly handles the `requestsFromUrl` option, meaning it can be also used with the `BasicCrawler.addRequests()` shortcut. Moreover, the batching is now configurable via `batchSize` and `waitBetweenBatchesMillis` options.
Closes #1995
=> feat(core): add `RequestQueue.addRequestsBatched()` that is non-blocking

.eslintrc.json, packages/basic-crawler/src/internals/basic-crawler.ts, packages/types/src/storages.ts, test/core/crawlers/basic_crawler.test.ts, test/e2e/cheerio-default/actor/main.js
Adds `statusMessageCallback` option to all the crawler classes to allow customizing the status message call.
> Allows overriding the default status message. The callback needs to call `crawler.setStatusMessage()` explicitly.
> The default status message is provided in the parameters.
```ts
const crawler = new CheerioCrawler({
statusMessageCallback: async (ctx) => {
return ctx.crawler.setStatusMessage(`this is status message from ${new Date().toISOString()}`, { level: 'INFO' }); // log level defaults to 'DEBUG'
},
statusMessageLoggingInterval: 1, // defaults to 10s
async requestHandler({ $, enqueueLinks, request, log }) {
// ...
},
});
```
=> feat(basic-crawler): allow configuring the automatic status message

packages/basic-crawler/src/internals/basic-crawler.ts, packages/browser-crawler/src/internals/browser-crawler.ts, packages/core/src/errors.ts, packages/core/src/request.ts, packages/http-crawler/src/internals/http-crawler.ts, packages/utils/src/internals/blocked.ts, test/core/crawlers/browser_crawler.test.ts, test/core/crawlers/cheerio_crawler.test.ts
When Crawlee sees a proxy-related error in navigation, it retires the current session and retries the request using another session (proxy).
closes #1912
=> feat: retire session on proxy error

packages/core/src/enqueue_links/shared.ts, test/core/enqueue_links/enqueue_links.test.ts
=> fix(core): support relative links in `enqueueLinks` explicitly provided via `urls` option

packages/playwright-crawler/package.json, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/package.json, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts, test/e2e/playwright-enqueue-links/actor/main.js, test/e2e/puppeteer-enqueue-links/actor/main.js, yarn.lock
Still somewhat WIP:
- You have to detect the modal yourself (and call the helper). For user comfort, it would probably be better if we did this somehow automatically.
- We have no data about the performance impact (of injecting 1.3MB JS file). Most of the script should get GC-ed immediately after running it, but who knows.
=> feat: add `closeCookieModals` context helper for Playwright and Puppeteer

README.md
=> docs: remove Apify SDK reference from readme

packages/browser-crawler/src/internals/browser-crawler.ts, packages/core/src/errors.ts, packages/http-crawler/src/internals/http-crawler.ts, test/core/crawlers/browser_crawler.test.ts, test/core/crawlers/cheerio_crawler.test.ts
The session rotation error message now contains the original proxy error for easier debugging.
=> fix: log original error message on session rotation

packages/basic-crawler/src/internals/basic-crawler.ts, test/core/crawlers/browser_crawler.test.ts, test/core/crawlers/cheerio_crawler.test.ts
Any request exceeding the `maxSessionRotations` limit currently kills the crawler. This was intended for early exit on too many hard proxy errors, but proved to be somewhat confusing for users using `retryOnBlocked` (any page that the crawler cannot access due to bot protection kills the run).
With this PR, the requests that cross the limit of `maxSessionRotations` now get processed with `failedRequestHandler`. Not sure if this is breaking (definitely might confuse a dev or two), but it's in line with how the crawlers worked before the `SessionError` update (so... it's actually reverting the hidden breaking change?)
Closes #2028
=> feat: exceeding maxSessionRotations calls failedRequestHandler

website/src/pages/index.js
Adds a new deployment section to the bottom of the homepage, describing how to deploy a crawlee project to apify platform.
=> docs: add deployment section to the homepage

packages/templates/templates/cheerio-js/src/routes.js, packages/templates/templates/cheerio-ts/src/routes.ts, packages/templates/templates/getting-started-js/src/main.js, packages/templates/templates/getting-started-ts/src/main.ts, packages/templates/templates/playwright-js/src/routes.js, packages/templates/templates/playwright-ts/src/routes.ts, packages/templates/templates/puppeteer-js/src/routes.js, packages/templates/templates/puppeteer-ts/src/routes.ts
Using the new dataset helpers from `3.5.3` in the Crawlee project templates simplifies integration with cloud services and helps with running multiple crawler instances in the templated projects.
=> chore: templates use new dataset helpers

docs/guides/request_storage.mdx, packages/core/src/storages/utils.ts, website/versioned_docs/version-3.5/guides/request_storage.mdx
Merge after this one is merged: https://github.com/apify/apify-sdk-js/pull/223
=> fix(core): allow explicit calls to `purgeDefaultStorage` to wipe the storage on each call

packages/basic-crawler/package.json, packages/http-crawler/package.json, packages/utils/package.json, yarn.lock
Updates `got-scraping` dependencies as the previous version fail on Node v18.
=> chore: bump got-scraping version (ada url issue)

packages/basic-crawler/src/internals/basic-crawler.ts
Following the trend of removing side-effects from the Crawlee codebase, this one looks pretty unintentional - the augmented context is passed to a handler, but the changes persist even after the handler is executed.
Fixes #2068
=> feat: remove side effect from the deprecated error context augmentation

packages/core/src/crawlers/statistics.ts, packages/core/src/storages/dataset.ts, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts
Various parts of Crawlee called `KVS.open()` which lead to possible shared state between multiple concurrent crawlers. This PR makes all those parts to open KVS only with the proper `Configuration` instance.
=> fix: various helpers opening KVS now respect Configuration

website/docusaurus.config.js, website/package.json, website/roa-loader/index.js
Adds `start:fast` script for faster docs development - in the `fast` mode, the code hashing and docs versions are disabled.
=> docs: add start:fast script for faster docs development

packages/basic-crawler/src/internals/basic-crawler.ts, packages/browser-crawler/src/internals/browser-crawler.ts, packages/cheerio-crawler/src/internals/cheerio-crawler.ts, packages/core/src/enqueue_links/enqueue_links.ts, packages/core/src/request.ts, packages/core/src/storages/index.ts, packages/core/src/storages/request_list.ts, packages/core/src/storages/request_provider.ts, packages/core/src/storages/request_queue.ts, packages/core/src/storages/request_queue_v2.ts, packages/core/src/storages/storage_manager.ts, packages/core/src/storages/utils.ts, packages/core/test/request-queue/request-queue-v2.test.ts, packages/jsdom-crawler/src/internals/jsdom-crawler.ts, packages/linkedom-crawler/src/internals/linkedom-crawler.ts, packages/memory-storage/src/resource-clients/request-queue.ts, packages/playwright-crawler/src/internals/enqueue-links/click-elements.ts, packages/puppeteer-crawler/src/internals/enqueue-links/click-elements.ts, test/core/storages/request_queue.test.ts, test/e2e/cheerio-request-queue-v2/actor/.actor/actor.json, test/e2e/cheerio-request-queue-v2/actor/.gitignore, test/e2e/cheerio-request-queue-v2/actor/Dockerfile, test/e2e/cheerio-request-queue-v2/actor/main.js, test/e2e/cheerio-request-queue-v2/actor/package.json, test/e2e/cheerio-request-queue-v2/test.mjs
=> feat: Request Queue v2

packages/core/src/storages/request_provider.ts, packages/core/src/storages/request_queue.ts, packages/core/src/storages/request_queue_v2.ts
Resolves compile errors like
```
2023-09-25T10:09:25.017Z src/main.ts:37:5 - error TS2739: Type 'BuiltRequestProvider' is missing the following properties from type 'RequestQueue': _listHeadAndLockPromise, _listHeadAndLock, getOrHydrateRequest, _prolongRequestLock, _clearPossibleLocks
2023-09-25T10:09:25.018Z 37     requestQueue = await RequestQueueV2.open();
2023-09-25T10:09:25.019Z        ~~~~~~~~~~~~
2023-09-25T10:09:25.020Z src/main.ts:60:5 - error TS2322: Type 'BuiltRequestProvider' is not assignable to type 'RequestQueue'.
2023-09-25T10:09:25.021Z 60     requestQueue = await RequestQueueV2.open(requestQueueId);
2023-09-25T10:09:25.023Z        ~~~~~~~~~~~~
```
=> fix(types): make return type of RequestProvider.open and RequestQueue(v2).open strict and accurate

packages/utils/src/internals/blocked.ts
Closes apify/store-website-content-crawler#154.
Related [Slack thread here](https://apifier.slack.com/archives/C05683VTD6J/p1695918076069999).
=> feat: add incapsula iframe selector to the blocked list

packages/basic-crawler/src/internals/basic-crawler.ts, test/core/crawlers/browser_crawler.test.ts
=> fix: add warning when we detect use of RL and RQ, but RQ is not provided explicitly

packages/basic-crawler/src/internals/basic-crawler.ts, packages/core/src/storages/request_provider.ts
Until now, the `assumedTotalCount` got reset on a migration (it was a purely local counter). This causes #1855, which is not too bad, but manifests at a very prominent place in the console. 
I'm not *way too confident* about the async iife in the constructor, but I think it should work just fine, as the new `totalCount` property is purely approximative (and is marked as such it the comment).
Closes #1855
=> fix: RQ request count is consistent after migration

packages/utils/src/internals/extract-urls.ts
This should protect us from OOM errors when processing a very large URL list.
=> fix: refactor `extractUrls` to split the text line by line first

packages/core/src/storages/request_list.ts
The docs and comments metioned the constructor and `.initialize()`, which are now private
`{ ...{test: "value"}, test: undefined }` results in `{test: undefined}`, so the overrides didn't work properly
=> fix(core): respect some advanced options for `RequestList.open()` + improve docs

packages/browser-pool/src/abstract-classes/browser-plugin.ts, packages/browser-pool/src/index.ts, packages/browser-pool/src/playwright/playwright-plugin.ts, packages/browser-pool/src/puppeteer/puppeteer-plugin.ts, packages/browser-pool/test/new-errors.test.ts
This enhances the default stack trace and messages for browser pool launch errors to directly mention what went wrong (as some loggers may not include the `cause` property to be logged, which is quite critical for debugging what went wrong)
=> fix: provide more detailed error messages for browser launch errors

test/e2e/cheerio-throw-on-ssl-errors/test.mjs
Ever since Oct 10, the Cheerio SSL errors test has been failing in Crawlee. This is because before, Crawlee managed to process the https://no-sct.badssl.com/ website, but now it doesn't (failing with various errors like "expired certificate" and "unable to verify the first certificate"). This error now happens even on the last-known-working commit built with `yarn --immutable`.
Inspired by [the fix from the JS SDK](https://github.com/apify/apify-sdk-js/pull/247/) :) Perhaps @vladfrangu did you learn something about the error when looking into it?
=> fix: e2e cheerio-throw-on-ssl-errors

.github/workflows/test-ci.yml, packages/basic-crawler/src/internals/basic-crawler.ts, packages/core/src/storages/dataset.ts, test/core/crawlers/basic_crawler.test.ts
Retrieves all the data from the default crawler `Dataset` and exports them to the specified format. Supported formats are currently 'json' and 'csv', and will be inferred from the `path` automatically.
```ts
const crawler = new BasicCrawler({ ... });
crawler.pushData({ ... });
await crawler.exportData('./data.csv');
```
=> feat(core): add `crawler.exportData()` helper

packages/browser-crawler/src/internals/browser-crawler.ts, packages/browser-pool/src/puppeteer/puppeteer-plugin.ts, packages/playwright-crawler/src/internals/playwright-crawler.ts, packages/puppeteer-crawler/src/internals/puppeteer-crawler.ts, packages/puppeteer-crawler/src/internals/puppeteer-launcher.ts, test/core/puppeteer_request_interception.test.ts, test/core/puppeteer_utils.test.ts, test/shared/_helper.ts
https://developer.chrome.com/articles/new-headless/
To opt out of it and keep using the old headless, add `headless: 'old` to your puppeteer crawler options.
=> feat(puppeteer): enable `new` headless mode

website/src/css/custom.css
Articles collapse to the width of their content. If the content is too short, it looks weird.
| before | after |
|---|---|
| ![obrazek](https://github.com/apify/crawlee/assets/61918049/71088a43-9ae6-40ff-b3ff-2f0cfe405b17) | ![obrazek](https://github.com/apify/crawlee/assets/61918049/7657c3ae-dfba-409e-a07f-236093a17440) |
Tested in mobile too, all should work fine.
CC @janbuchar thanks for the report
=> docs: set fixed width for short docs articles

packages/core/src/storages/request_list.ts, packages/core/src/storages/request_provider.ts
If the user submits a list of invalid URLs (e.g. without the `protocol` part), the message about an "empty" list can get confusing.
Mentioned in https://console.apify.com/actors/aYG0l9s7dbB7j3gbS/issues/pGohDSeaCzL4xZ2bI
=> docs: improve warning message on empty RequestList

packages/cli/src/commands/RunProjectCommand.ts
Side effect: it'll also pass down any other env variables that users provide (so for instance CRAWLEE_LOG_LEVEL, or w/e)
=> fix: make CLI work on Windows too with `--no-purge`

packages/browser-crawler/src/internals/browser-crawler.ts, packages/core/src/session_pool/consts.ts, packages/core/src/session_pool/index.ts, packages/core/src/session_pool/session_pool.ts, packages/utils/src/internals/blocked.ts, test/core/crawlers/browser_crawler.test.ts, test/shared/_helper.ts
With the `retryOnBlocked` option on, the crawler passes HTTP status `429` without throwing an error (the blocked status codes are overridden because of how the Cloudflare challenge works). 
This PR adds a check for the `blockedStatusCodes` after the "blocking" selectors are queried.
=> fix: `retryOnBlocked` doesn't override the blocked HTTP codes

packages/basic-crawler/src/internals/basic-crawler.ts, packages/core/src/crawlers/statistics.ts, packages/core/src/session_pool/session_pool.ts
Allow disabling automatic persistence in Statistics and SessionPool.
Add additional methods for manual disabling in case it's needed, but just not the automatic one
Closes #1789
=> feat: allow configuring crawler statistics

packages/templates/templates/cheerio-ts/tsconfig.json, packages/templates/templates/getting-started-ts/tsconfig.json, packages/templates/templates/playwright-ts/tsconfig.json, packages/templates/templates/puppeteer-ts/tsconfig.json, packages/utils/package.json, scripts/typescript_fixes.mjs, yarn.lock
=> fix: ES2022 build compatibility and move to NodeNext for module

packages/utils/src/internals/blocked.ts
We only want the `CLOUDFLARE_RETRY_CSS_SELECTORS` to target the Cloudflare "challenge page", not the invisible Turnstile element (the Cloudflare alternative to Captcha - also included in the challenge page) as the Turnstile widget can be just rendered into the page (along with all the other content).
Closes #2256
=> fix: pass on an invisible CF turnstile

packages/core/src/enqueue_links/shared.ts, test/core/enqueue_links/enqueue_links.test.ts
Was noticed as an issue when running through apify where we'd get an empty element that throws a very non descriptive error
Reported here: https://console.apify.com/actors/aYG0l9s7dbB7j3gbS/issues/Wd0Ahfk9Vd2OPk4Uf
=> fix: filter out nullish globs

packages/browser-pool/src/fingerprinting/types.ts, packages/browser-pool/src/fingerprinting/utils.ts
<details>
<summary>Old PR description</summary>
I think we may want to add an alias for the resulting type using BrowserName.
Typechecking and tests are running fine.
What do you guys think ?
</details>
This PR aims to allow the `BrowserName` enum to be used :
- in TS < 5, with `isolatedModules`
- in TS >= 5, with `verbatimModuleSyntax`
Removing the `const` modifier, does not break the runtime nor the typing.
=> refactor(browser-pool): drop const modifier for BrowserName enum

packages/basic-crawler/src/internals/basic-crawler.ts, packages/core/src/crawlers/crawler_commons.ts
- `getKeyValueStore` - replacement for direct `KeyValueStore.open` calls
- `addRequests`, `useState` - basically shortcuts to the respective methods on the `crawler`
- `pushData` and `getDataset` - there's a new parameter that allows changing the target dataset
These changes should help the users avoid touching global `Dataset` and `KeyValueStore` instances and the `crawler` field. Not touching global crawlee/apify-sdk stuff should become **the way** to write request handlers, piece by piece. 
A subset of the `CrawlingContext` interface that should be enough for the vast majority of use cases. This is not used anywhere yet. If a user sticks to using this, the side-effects of the request handler should be well contained - we can for example run a request handler with a mock implementation …
=> feat: accessing crawler state, key-value store and named datasets via crawling context

packages/basic-crawler/package.json, yarn.lock
a quick win where this is the only thing that prevents crawlee from running via yarn pnp out of the box. the basic-crawler package was using two dependencies not specified in its package.json (`csv-stringify` and `fs-extra`) as also mentioned by running `yarn dlx @yarnpkg/doctor ./packages/basic`:
```
➤ YN0000: ┌ /home/reda/Documents/Projects/forks/crawlee/packages/basic-crawler/package.json
➤ YN0000: │ /home/reda/Documents/Projects/forks/crawlee/packages/basic-crawler/src/internals/basic-crawler.ts:54:1: Undeclared dependency on csv-stringify
➤ YN0000: │ /home/reda/Documents/Projects/forks/crawlee/packages/basic-crawler/src/internals/basic-crawler.ts:55:1: Undeclared dependency on fs-extra
➤ YN0000: │ /home/reda/Documents/Projects/forks/crawlee/packages/basic-crawler/src/internals/basic-c …
```
=> fix: declare missing dependencies on `csv-stringify` and `fs-extra`

packages/browser-pool/src/puppeteer/puppeteer-plugin.ts
Fix [this bug](https://github.com/apify/crawlee/issues/2327) that caused the error "Could not kill browser: Cannot read private member #process from an object whose class did not declare it" when trying to close a Puppeteer browser (via `browserController.close();`).
Closes 2327
=> fix(puppeteer): add 'process' to the browser bound methods

packages/core/src/enqueue_links/shared.ts, packages/core/test/enqueue_links/user-provided-patterns-with-enqueue-strategy.test.ts
`createRequests` - and, transitively, `enqueueLinks` didn't work (imo) correctly when supplied only with `exclude` patterns.
In this case, `enqueueLinks` simply discarded the `exclude` patterns, enqueueing all the links (e.g. from the `urls` option). This is easy to see when you take a look at the original implementation of `createRequests`. 
This PR fixes that (and streamlines the `createRequests` implementation) - for every new potential request, we now:
- get its URL
- filter it out if it matches any of the `excludePatterns`
- create a `Request` object out of it 
- if there are no positive patterns supplied, just create a vanilla `Request` object
- if there are some positive patterns supplied, create a flavoured `Request` object, based on the matching pattern
- if the request didn't …
=> fix: `createRequests` works correctly with `exclude` (and nothing else)

packages/utils/src/internals/robots.ts, packages/utils/test/robots.test.ts
Previously, `RobotsFile.isAllowed()` always used the rules for `*` user agent, now this is configurable (keeping the `*` as default).
Also adds `RobotsFile.from()` helper to create the `RobotsFile` instance from the robots.txt content instead of querying the actual file.
Related: https://apifier.slack.com/archives/C0KRTKQD8/p1707985775359589
=> feat(core): add `userAgent` parameter to `RobotsFile.isAllowed()` + `RobotsFile.from()` helper

packages/core/src/storages/key_value_store.ts, packages/memory-storage/src/resource-clients/key-value-store.ts, packages/types/src/storages.ts, test/core/storages/key_value_store.test.ts
Testing for record existence with `getValue()` puts an unnecessary load on the Apify Platform / the storage backend - the client has to load the value just to throw it away in the next step.
`recordExists()` tests for the existence of a KVS key-value pair without actually retrieving the value itself.
---
side note: we should probably bump the `apify-client` dependency in `apify-sdk`, release a new version(?) and have Crawlee depend on this (and greater) versions of `apify-sdk`, right? 
Also, it's been some time since I did something with the storages, what's the procedure there? Are we still maintaining the `apify-storage-local` package - if so, we should probably add this method there as well
=> feat: `KeyValueStore.recordExists()`

packages/browser-pool/src/puppeteer/puppeteer-controller.ts, packages/browser-pool/src/puppeteer/puppeteer-plugin.ts
This fixes a regression introduced via #2337 which is not yet released to stable, hence keeping it outside of the changelog.
=> test: do not import puppeteer directly from inside browser pool

packages/core/src/autoscaling/autoscaled_pool.ts
I found an unused private property while reading the code and couldn't figure out why it's there - can we get rid of it?
=> chore: remove unused poolPromise property on AutoscaledPool

package.json, packages/basic-crawler/src/internals/basic-crawler.ts, packages/browser-crawler/package.json, packages/browser-crawler/src/internals/browser-crawler.ts, packages/core/src/crawlers/crawler_commons.ts, packages/core/src/crawlers/statistics.ts, packages/core/src/enqueue_links/enqueue_links.ts, packages/core/src/enqueue_links/shared.ts, packages/playwright-crawler/package.json, packages/playwright-crawler/src/index.ts, packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts, packages/playwright-crawler/src/internals/rendering-type-prediction.ts, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/playwright-crawler/src/internals/utils/rendering-type-prediction.ts, packages/playwright-crawler/src/logistic-regression.d.ts, test/core/crawlers/adaptive_playwright_crawler.test.ts, test/shared/MemoryStorageEmulator.ts, yarn.lock
This uses the newly added restricted crawling contexts to execute request handlers. This allows us to compare browser and http-only request handler runs for a request and switch to http-only crawling on sites that we predict to be static. More information will be added here.
The intended usage is as follows:
```ts
import { AdaptivePlaywrightCrawler } from 'crawlee';
const startUrls = [{url: 'https://warehouse-theme-metal.myshopify.com/collections', label: 'START'}];
const crawler = new AdaptivePlaywrightCrawler({
requestHandler: async ({ request, enqueueLinks, pushData, querySelector }) => {
console.log(`Processing: ${request.url} (${request.label})`);
if (request.label === 'DETAIL') {
const urlPart = request.url.split('/').slice(-1); // …
```
=> feat: adaptive playwright crawler

packages/utils/src/internals/sitemap.ts, packages/utils/test/sitemap.test.ts
I have encountered an issue when trying to decompress an invalid gzip sitemap file with the `RobotsFile` util provided by crawlee. When the gzip file is malformed, an error occurs, that crashes the entire node process. This error cannot be catched by consumers of the library.
A reproduction and more information about this issue can be found here: https://github.com/CakeWithDivinity/crawlee-sitemap-error
This is the error reporting the crash of the node process from my reproduction repo:
This is what it looks like after implementing my fix:
=> fix: correctly report gzip decompression errors

packages/basic-crawler/src/internals/basic-crawler.ts, packages/browser-crawler/src/internals/browser-crawler.ts, packages/browser-pool/src/abstract-classes/browser-controller.ts, packages/browser-pool/src/abstract-classes/browser-plugin.ts, packages/browser-pool/src/browser-pool.ts, packages/browser-pool/src/launch-context.ts, packages/core/src/proxy_configuration.ts, packages/core/src/request.ts, packages/http-crawler/src/internals/http-crawler.ts, test/core/crawlers/basic_crawler.test.ts, test/core/crawlers/cheerio_crawler.test.ts, test/core/proxy_configuration.test.ts
Introduces the `tieredProxyUrls` option for `ProxyConfigration`, allowing the user to pass proxy URL groups. 
The `newProxyInfo` now takes an optional `request` parameter, which can be used for picking the correct proxy tier. Because of this, the proxy tiering doesn't work properly in browser crawlers without `useIncogintoPages` (as the proxy is tied to the launched browser instance and can be used for multiple requests).
To do:
- maybe figure out the tiers for `useIncognitoPages: false`
- use `sessionId` with the `tieredProxyUrls` - would require tracking the `session - URL - proxyTier` mapping, which might be a lot of data for large crawls... still worth trying out.
=> feat: `tieredProxyUrls` for ProxyConfiguration

test/core/playwright_utils.test.ts
I remember dealing with this once already - when injecting HTML using `setContent` to `about:blank`, you confuse the browser into thinking that some weird CORS (more precisely, ORB) situation is going on. Loading the page on the correct domain (same as the subresources) mitigates this issue.
=> test: circumvent ORB in `blockRequests` tests

packages/basic-crawler/src/internals/basic-crawler.ts, packages/core/src/autoscaling/autoscaled_pool.ts
Notify AutoscaledPool when calling `crawler.addRequests()`. This is important for crawlers in `keepAlive` mode that might have an empty queue and we don't want to wait till the next scheduled check (which might come in as much as 500ms by default).
Related: https://apify.slack.com/archives/CD0SF6KD4/p1711660060498849
=> fix: notify autoscaled pool about newly added requests

packages/browser-crawler/src/internals/browser-crawler.ts, packages/browser-pool/src/abstract-classes/browser-controller.ts, packages/browser-pool/src/browser-pool.ts, packages/core/src/proxy_configuration.ts, test/core/proxy_configuration.test.ts
Based on changes from #2348 , this PR simplifies the proxy handling in the browser crawlers and makes those more intuitive.
Ready for reviews!
Closes #2065
=> feat: better `newUrlFunction` for ProxyConfiguration

packages/browser-crawler/src/internals/browser-crawler.ts, packages/playwright-crawler/src/internals/playwright-crawler.ts, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/src/internals/puppeteer-crawler.ts, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts, packages/utils/src/internals/general.ts, test/core/playwright_utils.test.ts, test/core/puppeteer_utils.test.ts
Custom HTML elements have their content isolated under a `#shadow-root` property, this PR handles its expansion by traversing the DOM and looking for all custom components with a shadow root, inlining its contents. This way, we can traverse the inside of a custom component via cheerio, as well as get the text content later on.
The behavior is enabled by default and can be disabled via `ignoreShadowRoots: true` in the crawler options.
=> feat: expand #shadow-root elements automatically in `parseWithCheerio` helper

packages/utils/src/internals/robots.ts, packages/utils/src/internals/sitemap.ts
Some websites (e.g. https://www.topprodukte.at/xml_sitemap) return sitemaps with `application/xml` MIME type. 
According to [StackOverflow](https://stackoverflow.com/questions/4832357/whats-the-difference-between-text-xml-vs-application-xml-for-webservice-respons), this should be interchangeable with `text/xml` and we should therefore support it.
Also fixes some small typos in the `RobotsFile` jsdoc.
=> fix: sitemaps support `application/xml`

packages/core/src/router.ts, packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
- closes #2407
- the function itself makes it easier to use a Router for
structured adaptive crawling
- in this PR, we also export the `AdaptivePlaywrightCrawlerContext` type
and relax the type parameter constraint on `Router` to `RestrictedCrawlingContext`
=> feat: `createAdaptivePlaywrightRouter` utility

packages/core/src/autoscaling/autoscaled_pool.ts
=> fix: break up growing stack in `AutoscaledPool.notify`

packages/utils/src/internals/sitemap.ts, packages/utils/test/sitemap.test.ts
During [fixing](https://github.com/topmonks/hlidac-shopu/pull/2109) Mironet actor for HlidacShopu, I've encountered CDATA in sitemap for the first time in my life. Not sure how common it is in real world.
https://www.mironet.cz/sm/sitemap_kategorie_p_1.xml.gz
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc><![CDATA[https://www.mironet.cz]]></loc>
<lastmod>2024-04-16</lastmod>
<changefreq>daily</changefreq>
<priority>0.9</priority>
</url>
``` 
This PR is just a quickest implementation I could come up with. Feel free to make any changes or to disagree that it should be included in crawlee core :)
=> feat(sitemap): Support CDATA in sitemaps

packages/utils/src/internals/sitemap.ts, packages/utils/test/sitemap.test.ts
Fixes https://github.com/apify/crawlee/issues/2420
=> fix: malformed sitemap url when sitemap index child contains querystring

website/src/pages/index.js, website/src/pages/index.module.css
Before:
After:
Switching:
The antialiasing on the font seems to be calculated from the final `background` layer(?) - in the case of the gradient-colored text, the lowest layer was gray(?), the fringe didn't match the font/background color and was causing unappealing results.
As a bonus, the users still get the text highlight, even if their browser couldn't render the gradient for some reason.
=> docs: mitigate logotype "aliasing" on homepage

packages/utils/src/internals/robots.ts
`undefined` means that there is no explicit rule for the requested route. No rules means no disallow, therefore it's allowed.
Fixes #2437
=> fix: return true when robots.isAllowed returns undefined

website/versioned_docs/version-3.9/examples/crawl_relative_links.mdx
The docs appear to be a bit misleading. If people want "Same Subdomain" they should actually use "Same Hostname".
=> docs: Should be "Same Domain" not "Same Subdomain"

packages/utils/package.json, packages/utils/src/internals/sitemap.ts, yarn.lock
According to the [RFC1341](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html), the Content-type header can contain additional string parameters. 
This is sometimes used to communicate the encoding of the content (or other stuff(?)), like in `text/plain; charset=utf-8`.
The current sitemap implementation didn't expect this and skipped perfectly good sitemaps.
=> fix: sitemap `content-type` check breaks on `content-type` parameters

packages/core/src/configuration.ts
During local development, we are firing events for the AutoscaledPool about current system resources like memory or CPU. We were firing them once a minute by default, but we remove those snapshots older than 30s, so we never had anything to compare and always used only the very last piece of information.
This PR changes the interval to 1s, aligning this with how the Apify platform fires events.
=> fix(core): fire local `SystemInfo` events every second

packages/core/src/storages/request_provider.ts
This PR resolves three main issues with adding large amount of requests into the queue:
- Every requests added to the queue was automatically added to the LRU requests cache, which has a size of 1 million items. this makes sense for enqueuing a few items, but if we try to add more than the limit, we end up with overloading the LRU cache for no reason. Now we only add the first 1000 requests to the cache (plus any requests added via separate calls, e.g. when doing `enqueueLinks` from inside a request handler, again with a limit of the first 1000 links).
- We used to validate the whole requests array via `ow`, and since the shape can vary, it was very slow (e.g. 20s just for the `ow` validation). Now we use a tailored validation for the array that does the same but resolves within 100ms or …
=> perf: optimize adding large amount of requests via `crawler.addRequests()`

packages/basic-crawler/src/internals/basic-crawler.ts, packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
This fixes a bug that was introduced with https://github.com/apify/crawlee/pull/1844 and https://github.com/apify/crawlee/pull/2083 - we reset the persisted state for statistics and session pool each time a crawler is started, which prevents their restoration.
=> fix: do not drop statistics on migration/resurrection/resume

packages/core/src/proxy_configuration.ts
Mitigates an index-out-of-bounds error that happens in a certain scenario of tier switching.
Repro by @VojtaM39
```typescript
import { Actor } from 'apify';
import { CheerioCrawler } from 'crawlee';
await Actor.init();
const proxyConfiguration = await Actor.createProxyConfiguration({
tieredProxyConfig: [
{ groups: [] },
{ groups: ['RESIDENTIAL'] },
],
});
const crawler = new CheerioCrawler({
proxyConfiguration,
maxRequestRetries: 3,
requestHandler: async () => {
throw new Error('test');
},
});
await crawler.run([{ url: 'http://example.com/', skipNavigation: true }]);
await Actor.exit();
```
=> fix: double tier decrement in tiered proxy

packages/core/src/session_pool/session_pool.ts
Changes SessionPool's new Session loading behavior in the core module to utilize the configured createSessionFunction if specified. This ensures that new Sessions are instantiated using the custom session creation logic provided by the user, improving flexibility and adherence to user configurations.
=> fix(core): use createSessionFunction when loading Session from persisted state

packages/core/src/cookie_utils.ts, test/core/session_pool/session.test.ts
Fixes the conversion from tough cookies to browser pool cookies and vice versa, by correctly handling cookies where the domain has a leading dot versus when it doesn't.
=> fix(core): conversion between tough cookies and browser pool cookies

docs/examples/crawl_sitemap.mdx, docs/examples/crawler-plugins/index.mdx, docs/examples/http_crawler.mdx, docs/examples/http_crawler.ts, docs/guides/cheerio_crawler.mdx, website/src/components/Highlights.jsx
@B4nan please don't merge it yet.
@davidjohnbarton can you please look into changes?
=> docs: improve crawlee seo ranking

packages/core/src/crawlers/statistics.ts
Those fields are duplicated in the base class anyway.
=> refactor: Remove redundant fields from `StatisticsPersistedState`

packages/core/src/crawlers/error_snapshotter.ts, packages/core/src/crawlers/error_tracker.ts, packages/core/src/storages/key_value_store.ts, test/e2e/cheerio-error-snapshot/test.mjs, test/e2e/puppeteer-error-snapshot/test.mjs
This will respect the Actor SDK override automatically since importing the SDK will fire this side effect: 
https://github.com/apify/apify-sdk-js/blob/master/packages/apify/src/key_value_store.ts#L25
=> fix: provide URLs to the error snapshot

packages/utils/src/internals/general.ts, test/shared/data/simple_url_list.txt
=> fix: adjust `URL_NO_COMMAS_REGEX` regexp to allow single character hostnames

packages/utils/package.json, packages/utils/src/internals/sitemap.ts, packages/utils/test/sitemap.test.ts, yarn.lock
=> fix: Autodetect sitemap filetype from content

website/package.json, website/patches/@docusaurus+core+3.4.0.patch, website/yarn.lock
Because of some on-page DOM modifications, the links with #fragment parts are not always aligned to the element with the correct id. 
I agree this is a quick remedy rather than an actual solution, but it's simple (and IMO) safe enough to do before we dive too deep into anything else. 
closes #2250
=> docs: wait before scrolling fragments into viewport

biome.json, packages/cheerio-crawler/src/internals/cheerio-crawler.ts, packages/core/src/crawlers/crawler_commons.ts, packages/http-crawler/src/internals/http-crawler.ts, packages/jsdom-crawler/src/internals/jsdom-crawler.ts, packages/linkedom-crawler/src/internals/linkedom-crawler.ts, packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts, scripts/typescript_fixes.mjs, test/core/crawlers/adaptive_playwright_crawler.test.ts, test/core/crawlers/http_crawler.test.ts, test/e2e/playwright-enqueue-links-base/actor/main.js
This introduces a new `waitForSelector` context helper to all the crawler types. In browser based crawlers, it will wait for the element, in HTTP crawlers it will check if the selector can be found in the HTML and throw otherwise.
Also, the `parseWithCheerio` is now in adaptive crawler too, and it has a new parameter that allows waiting for a selector via `waitForSelector`.
=> feat: add `waitForSelector` context helper + `parseWithCheerio` in adaptive crawler

packages/basic-crawler/src/internals/basic-crawler.ts, packages/http-crawler/src/internals/http-crawler.ts
This is important for being able to easily change log level for the crawler.
```ts
crawler.log.setLevel(LogLevel.DEBUG);
```
=> fix: make `crawler.log` publicly accessible

packages/basic-crawler/src/internals/basic-crawler.ts, packages/browser-crawler/src/internals/browser-crawler.ts, packages/core/src/crawlers/crawler_commons.ts, packages/core/src/router.ts, packages/http-crawler/src/internals/http-crawler.ts, packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts, packages/playwright-crawler/src/internals/playwright-crawler.ts, test/core/crawlers/cheerio_crawler.test.ts
The properties are still optional in other places like `preNavigationHooks`.
=> fix: mark `context.request.loadedUrl` and `id` as required inside the request handler

packages/browser-crawler/package.json, packages/jsdom-crawler/package.json, yarn.lock
This PR fixes the errors thrown by yarn 4 when using crawlee in another project.
=> fix: declare missing peer dependencies in `@crawlee/browser` package

packages/browser-crawler/src/internals/browser-crawler.ts, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts, test/core/playwright_utils.test.ts, test/core/puppeteer_utils.test.ts, test/shared/_helper.ts
Replaces the `iframe` elements with their contents in `<div class="crawlee-iframe-replacement"></div>` element. 
Closes #2507
=> feat: add `iframe` expansion to `parseWithCheerio` in browsers

docs/examples/file_download.mdx, docs/examples/file_download.ts, docs/examples/file_download_stream.mdx, docs/examples/file_download_stream.ts, packages/http-crawler/src/internals/file-download.ts
Adds documentation examples for the `FileDownload` class and fixes type mismatch for the `stream` context field.
=> docs: file download examples

docs/guides/running-in-web-server/running-in-web-server.mdx, docs/guides/running-in-web-server/web-server.mjs
I took the Parallel Scraping guide as a template so please check that it makes sense. The code/example are really bare bones and there might be some code smells.
I checked that the example works and the text with Grammarly.
=> docs(guides): add 'Running in web server' guide

packages/browser-crawler/src/internals/browser-crawler.ts, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts
Allows to opt-out from the new `iframe` expansion feature in `parseWithCheerio` from https://github.com/apify/crawlee/commit/328d08598807782b3712bd543e394fe9a000a85d
=> feat: add `ignoreIframes` opt-out from the Cheerio iframe expansion

website/blog/2024/07-05-launching-crawlee-python/index.md, website/docusaurus.config.js, website/src/css/custom.css, website/src/pages/index.js, website/src/pages/index.module.css
This mentions https://github.com/apify/crawlee-python in the announcement bar and the top of the homepage, as well as adds a dropdown to the navbar to allow switching versions.
All the links except navbar go to the blog post from #2567 so that one should be merged first.
=> docs: mention python version on homepage/navbar/announcement bar

packages/utils/src/internals/general.ts, test/core/playwright_utils.test.ts, test/core/puppeteer_utils.test.ts, test/shared/_helper.ts
`expandShadowRoots` now does not replace the original content but creates a separate (non-shadow) subtree as a sibling of the original one. 
Note that this doesn't duplicate content $\^{[1\]}$ , as the original shadow roots are inaccessible from JS by design. `document.documentElement.outerHTML` returns only the contents of (new) regular DOM elements. The page also still looks the same, as a shadow DOM tree [masks any "light" DOM sibling](https://stackoverflow.com/questions/47500157/shadow-root-sibling-elements-disappear-on-attachshadow-call).
Closes #2583 
------
$^{[1]}$ With the notable exception of [accessgroup.my.site.com](https://accessgroup.my.site.com/Support/s/article/Access-Capture-Error-Cant-reach-this-page-when-trying-to-access-the-Capture-web-page) pages, where the use of …
=> fix: use `getHTML` in the shadow root expansion

website/docusaurus.config.js, website/src/pages/index.js
Removes the large "hero" banner advertising Crawlee for Python (keeps the top bar). Changes the link in the top bar to the actual `crawlee.dev/python` docs page instead of the blog post.
=> docs: tweak the Crawlee for Python links

README.md
Added missing mention of Crawlee for Python in readme.
=> docs: add crawlee python mention in readme

packages/core/src/storages/sitemap_request_list.ts, packages/utils/src/internals/sitemap.ts, test/core/sitemap_request_list.test.ts
Adds:
Allows users to signal that they won't need the `SitemapRequestList` instance anymore (so the sitemap loading can stop and trash all pending URLs). Internally, this unblocks the waiting `pushNextUrl` calls and allows the runtime environment to terminate correctly.
Network errors do not crash the `parseSitemap()` or `SitemapRequestList.load()` calls anymore. Instead, the sitemap load is retried (plus, with `SitemapRequestList`, the URLs aren't duplicated if the error happened somewhere in the middle of the sitemap load).
Both `parseSitemap()` and `SitemapRequestList.load()` calls now accept got-like timeout object (see [more details here](https://github.com/sindresorhus/got/blob/main/documentation/6-timeout.md)). This can help with issues described in …
=> feat: resilient sitemap loading

packages/core/src/autoscaling/autoscaled_pool.ts
=> docs: remove duplicated `the` in AutoscaledPool

packages/core/src/storages/sitemap_request_list.ts, test/core/sitemap_request_list.test.ts
Adds `globs`, `regexps` and `exclude` options to `SitemapRequestList` to make it list only URLs that match those patterns.
While this looked like a single-responsibility violation to me at first, these changes are imo quite justifiable, as the possible use cases (wanting to crawl only a part of a website while utilizing the official sitemap) seem to be very sane.
=> feat: `globs` & `regexps` for `SitemapRequestList`

packages/utils/src/internals/cheerio.ts, packages/utils/src/internals/social.ts, test/utils/cheerio.test.ts
We keep the last RC pinned in the dependencies for now, but is just a forward upgrade which is compatible with both versions.
=> fix: use namespace imports for cheerio to be compatible with v1

packages/utils/src/internals/social.ts, test/utils/social.test.ts
Older Facebook URLs could be formatted like this:
`https://www.facebook.com/some-profile-1234`
This package currently incorrectly parses the URL as:
`https://www.facebook.com/some`
The REGEX for this package does not match the `-` character. These URLs have been deprecated, and Facebook will redirect these older style URLs to their newer style. We should still match these older style URLs as they are indeed valid, albeit old.
I've added 2 tests to cover these URL patterns, happy to adjust to any feedback.
Closes #2216
=> fix: improve `FACEBOOK_REGEX` to match older style page URLs

packages/core/src/storages/sitemap_request_list.ts, packages/utils/src/internals/general.ts, test/core/sitemap_request_list.test.ts
Pushing to the internal stream in `persistState` at https://github.com/apify/crawlee/blob/f3eb99d9fa9a7aa0ec1dcb9773e666a9ac14fb76/packages/core/src/storages/sitemap_request_list.ts#L446 caused uncaught exceptions if the stream was already closed.
closes #2672
=> fix: `SitemapRequestList.teardown()` doesn't break `persistState` calls

packages/browser-crawler/src/internals/browser-crawler.ts, test/e2e/puppeteer-ignore-ssl-errors/actor/main.js, test/e2e/puppeteer-throw-on-ssl-errors/actor/main.js
Both options are now used internally, since those code paths are shared for playwright as well, and we want to support older puppeteer versions too.
Also tested this locally with puppeteer v22, luckily there are no runtime validations for unknown options, so we can just use both.
=> fix(puppeteer): rename `ignoreHTTPSErrors` to `acceptInsecureCerts` to support v23

packages/basic-crawler/src/internals/basic-crawler.ts, test/core/crawlers/basic_crawler.test.ts
=> fix(core): trigger `errorHandler` for session errors

packages/core/src/request.ts, packages/core/src/serialization.ts, packages/core/src/storages/key_value_store.ts, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts
This fixes saving screenshots via puppeteer v23, which started returning `UInt8Array` instead of a `Buffer`.
All places where we had a validation for Buffer now also accept `UInt8Array`.
=> fix(core): accept `UInt8Array` in `KVS.setValue()`

packages/http-crawler/src/internals/http-crawler.ts, test/core/crawlers/http_crawler.test.ts
When the response is from cache, http-crawler will throw "TypeError: Cannot convert undefined or null to object"
This PR fixes this issue. Related usage is added as test case as well.
=> fix(http-crawler): avoid crashing when gotOptions.cache is on

packages/memory-storage/src/resource-clients/request-queue.ts, packages/memory-storage/test/request-queue/forefront.test.ts
Turns out we neglected the `prolong` and `deleteRequestLock` methods with #2681 , so these do not respect the `forefront`-enforced request ordering. This PR fixes this omission.
Prerequisite for #2689 
Related to #2669
=> fix: `prolong-` and `deleteRequestLock` `forefront` option

packages/core/src/storages/request_provider.ts, packages/core/src/storages/request_queue_v2.ts, test/core/storages/request_queue.test.ts
Keeps count of the (locally) `forefront` enqueued requests in the RQv2 instance. Uses this counter to signal the need for new remote RQ reads.
Note that with the current API, we cannot solve this for request queues with multiple clients. The original behavior is retained in such a scenario.
Closes #2669
=> fix: `forefront` request fetching in RQv2

packages/basic-crawler/src/internals/basic-crawler.ts
Adds a simple `.isFinished()` check before the `RequestList.fetchNextRequest()` call. This eliminates long-blocking calls with non-trivial `RequestList` implementations (e.g. `SitemapRequestList` in some edge cases).
=> fix: check `.isFinished()` before `RequestList` reads

packages/core/src/proxy_configuration.ts, test/core/proxy_configuration.test.ts
When using `newProxyInfo` function, the `username` and `password` extracted from `proxyUrl` are now properly decoded.
https://apify.slack.com/archives/C0L33UM7Z/p1727966399183259
=> fix: decode special characters in proxy `username` and `password`

packages/browser-pool/src/fingerprinting/types.ts
Manually cross-checked assignability against the types ([1](https://github.com/apify/fingerprint-suite/blob/c61814e6ba8822543deb0ce6c03e0a0249933629/packages/fingerprint-generator/src/fingerprint-generator.ts#L73),[2](https://github.com/apify/fingerprint-suite/blob/c61814e6ba8822543deb0ce6c03e0a0249933629/packages/header-generator/src/header-generator.ts#L87)) from `fingerprint-suite`. 
We should likely remove the enums below in the following breaking version too (in `fingerprint-suite`, we accept only string consts, which provides sufficient DX - regarding suggestions etc.). The current duplicity can cause more disparity down the road (adding new browsers to `fingerprint-suite` etc.).
Closes #2703
=> fix: update `fingerprintGeneratorOptions` types

packages/playwright-crawler/src/internals/utils/playwright-utils.ts, packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts
using try-except block to handle iframe content extraction error
with catch block Handle the error as needed and continue processing other frames
Closes #2708
=> fix: ignore errors from iframe content extraction

packages/core/src/storages/dataset.ts, test/core/storages/dataset.test.ts
=> fix(core): ensure correct column order in CSV export

renovate.json, website/docusaurus.config.js, website/package.json, website/src/css/custom.css, website/yarn.lock
Switches the `docusaurus-plugin-typedoc-api` for the Apify-managed fork. This allows us to use the recent patches for some smaller rendering issues. It also makes the Crawlee documentation setup consistent with all the other tooling-team-managed projects (all Python projects and JS SDK / Client already use this fork).
Closes #2266
=> docs: switch to the Apify-forked typedoc plugin

packages/core/src/proxy_configuration.ts
Since https://github.com/apify/crawlee/pull/2392, the `ProxyConfiguration` class is ready for `null` proxy "URLs" - this means that the proxy won't be used. 
This already worked with `newUrlFunction`, but because of types and validation, users couldn't use it with `tieredProxyUrls`.  
This PR relaxes the type checks and validation so we can use stuff like:
```typescript
new ProxyConfiguration({
tieredProxyUrls: [
[null], 
['http://proxy.apify.com', 'http://some.other.proxy.com']
],
})
```
and even 
```diff
new ProxyConfiguration({
tieredProxyUrls: [
-       [null], 
+       [null, 'http://some.local.cheap.proxy', 'http://other.local.cheap.proxy'], 
['http://proxy.apify.com', 'http://some.other.proxy.com']
],
})
```
Closes #2740
=> feat: `tieredProxyUrls` accept `null` for switching the proxy off

website/src/pages/index.js, website/src/pages/index.module.css
The inbuilt Docusaurus CSS minifier doesn't respect the CSS descendant combinator (likely treats it as an unused style and removes it from the build). This shows both with the nested CSS and the classic `a b` syntax. While related CSS issues (e.g. https://github.com/facebook/docusaurus/issues/9303) are already known to the Docusaurus team, this one still shows in the latest version (`docusaurus@3.6.3`).
This PR adds a separate CSS class for the transparent words in the tagline and explicitly sets this class on the relevant elements
=> docs: fix the Hero section tagline colors

website/package.json, website/yarn.lock
Context: https://apify.slack.com/archives/C0L33UM7Z/p1732811764451919
=> docs: bump typedoc-api plugin to mitigate stray React errors

packages/core/src/configuration.ts
We're planning to add a new environment variable, `ACTOR_BUILD_TAGS`, to the Actor runtime, which will contain the list of build tags of the currently running Actor build. The environment variable will be a comma-separated list, but I think it would be easier to work with if it was already parsed to an array in the `Configuration` instance.
This adds support for parsing comma-separated list environment variables to arrays. In the SDK, I'll then just override the `COMMA_SEPARATED_LIST_VARS` list to include the environment variable I want to have parsed.
=> feat: add support for parsing comma-separated list environment variables

packages/core/src/storages/dataset.ts, test/core/storages/dataset.test.ts
Fixes #2773 
I'm seeing type errors and test failures in `./test/core/sitemap_request_list.test.ts` both before and after my change.
This PR currently doesn't add tests to check that types resolve correctly. In the `reduce() uses first value as memo if no memo is provided` test, the result from reduce was previously inferred to be `any`, and is now inferred to be `Dictionary`. Adding a type annotation doesn't help catch this change as implicit any is allowed.
=> fix(core): type definition of Dataset.reduce

docs/introduction/05-crawling.mdx, website/versioned_docs/version-3.12/introduction/05-crawling.mdx
I'm not sure if this is the correct fix, but it does fix the problem, and it uses similar logic to the final script on this page, which is working properly.
(It also works if you simply comment out the `await page.waitForSelector('.collection-block-item');` line, but I assume that's there for a reason.)
Old output:
```
INFO  PlaywrightCrawler: All requests from the queue have been processed, the crawler will shut down.
INFO  PlaywrightCrawler: Final request statistics: {"requestsFinished":1,"requestsFailed":31,"retryHistogram":[1,null,null,31],"requestAvgFailedDurationMillis":30359,"requestAvgFinishedDurationMillis":1056,"requestsFinishedPerMinute":0,"requestsFailedPerMinute":6,"requestTotalDurationMillis":942186,"requestsTotal":32,"crawlerRuntimeMillis":291681}
INFO  PlaywrightCrawler: …
```
=> docs: Fix timeouts and retry limit exceeded in interim introduction example

packages/basic-crawler/src/internals/basic-crawler.ts
Allows users to actually use `await crawler.run([...], { purgeRequestQueue: false });`, which is a hard(?) requirement for stateful crawler use-cases.
Closes #2802
=> fix: destructure `CrawlerRunOptions` before passing them to `addRequests`

docs/guides/proxy_management.mdx, website/versioned_docs/version-3.12/guides/proxy_management.mdx
Adds separate sections for each `ProxyConfiguration` option and explains when to use which.
Related to #2778
=> docs: more details about different `ProxyConfiguration` options

.github/workflows/check-pr-title.yml, .github/workflows/docker-images.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/test-ci.yml, .github/workflows/test-e2e.yml, .github/workflows/update_new_issue.yml
While the [Playwright issue](https://github.com/microsoft/playwright/issues/30368) has been closed, the Playwright installation still struggles with the new Ubuntu 24 runner image. Pinning the image version should fix our CI tests and enable releases etc.
=> chore(ci): pin Ubuntu 22.04 because of Playwright dependencies

test/e2e/linkedom-default-ts/actor/main.ts
The e2e test have been failing since ~2 months ago because of the LinkeDOM test. 
This was happening because of the [brittle implementation](https://github.com/WebReflection/linkedom/blob/71399b5e9128d97e3de901eebad9ce8776793a96/cjs/html/document.js#L79) of the `title` method in LinkeDOM. On the (no JS) Crawlee homepage, there is no `<head>` element, so LinkeDOM doesn't find the `title` and returns empty string.
=> chore: fix the `LinkeDOM` e2e test

packages/basic-crawler/src/internals/basic-crawler.ts
Runs all the `BasicCrawler` clean-up actions even when the `AutoscaledPool.run()` throws.
Closes #2807
=> fix: graceful `BasicCrawler` tidy-up on `CriticalError`

packages/core/src/storages/key_value_store.ts, packages/core/src/storages/storage_manager.ts, test/e2e/kv-open-return-storage-object/actor/.actor/actor.json, test/e2e/kv-open-return-storage-object/actor/.gitignore, test/e2e/kv-open-return-storage-object/actor/Dockerfile, test/e2e/kv-open-return-storage-object/actor/main.js, test/e2e/kv-open-return-storage-object/actor/package.json, test/e2e/kv-open-return-storage-object/test.mjs
Currently, when opening a KV store, we only store the id and name from the get() response.
**This PR updates the logic to store the entire storageObject, allowing access to additional attributes without requiring extra requests.**
More context in [slack](https://apify.slack.com/archives/CD0SF6KD4/p1738936334553189)
=> refactor: set storage object on KV store open

packages/basic-crawler/src/internals/basic-crawler.ts
Clarifies the docstring for `BasicCrawler.run()`, specifying that the returned promise resolves **only when** `autoscaledPool.isFinished` returns `true`.  
Currently, the documentation implies that the promise resolves once all requests are processed, but this is misleading. If `autoscaledPoolOptions.isFinishedFunction` is set to always return `false`, the crawler never completes (e.g., in the case below):  
```ts
const crawler = new BasicCrawler({
autoscaledPoolOptions: {
isFinishedFunction: async () => {
return false;
},
},
});
await crawler.run([]);
=> docs: clarify `run()` resolve condition

test/e2e/cheerio-max-requests/test.mjs, test/e2e/kv-open-return-storage-object/actor/main.js, test/e2e/puppeteer-store-pagination-jquery/actor/main.js, test/e2e/puppeteer-store-pagination/actor/main.js
Fixes failing e2e tests from e.g. [here](https://github.com/apify/crawlee/actions/runs/13426528432/job/37510389928)
In `kv-open-return-storage-object`, adds missing `await` (caused the test to fail with Platform storage backend).
In `puppeteer-store-pagination-jquery-*`, this PR switches the network wait from the `networkIdle0` logic to `networkIdle2`. This way, the tests won't fail because of long-running requests. Note that the general use of `networkIdle` is discouraged, as it brings exactly this kind of issues. This risk is likely alright in our type of tests (and our controlled environment), though.
In `cheerio-max-requests` we set the `maxRequestsPerCrawl` to `10`. Expecting more than `10` requests in the test assert might be valid (due to concurrent processing), but can cause the …
=> chore: fix failing e2e tests

packages/templates/templates/camoufox-ts/Dockerfile, packages/templates/templates/camoufox-ts/package.json
Adds `postinstall` script to the `camoufox-ts` template's `package.json` to simplify first-time usage. Makes use of the new support for `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1` in `camoufox-js` to avoid multiple browser downloads during `docker build`.
=> chore: add `postinstall` script to `camoufox` template

packages/templates/templates/camoufox-ts/Dockerfile
Fixes a logical error introduced in #2863 . Base Apify Docker images set the `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` envvar, so the browser download is disabled by default. These changes reenable browser download in the production stage of the Docker build.
=> fix: install browser in the `camoufox` template correctly

docs/guides/avoid_blocking.mdx, docs/guides/avoid_blocking_camoufox.ts, package.json, packages/impit-client/src/index.ts, packages/playwright-crawler/src/internals/utils/playwright-utils.ts, test/e2e/camoufox-cloudflare/actor/.actor/actor.json, test/e2e/camoufox-cloudflare/actor/.gitignore, test/e2e/camoufox-cloudflare/actor/Dockerfile, test/e2e/camoufox-cloudflare/actor/main.js, test/e2e/camoufox-cloudflare/actor/package.json, test/e2e/camoufox-cloudflare/test.mjs, test/e2e/run.mjs, website/versioned_docs/version-3.12/guides/avoid_blocking.mdx, website/versioned_docs/version-3.12/guides/avoid_blocking_camoufox.ts, yarn.lock
Adds a new helper which should be able to get through Cloudflare checkbox challenge automatically when used with Camoufox.
```ts
import { PlaywrightCrawler } from 'crawlee';
import { launchOptions } from 'camoufox-js';
import { firefox } from 'playwright';
const crawler = new PlaywrightCrawler({
postNavigationHooks: [
async ({ handleCloudflareChallenge }) => {
await handleCloudflareChallenge();
},
],
launchContext: {
launcher: firefox,
launchOptions: await launchOptions({
headless: true,
}),
},
// ...
});
```
=> feat: add `handleCloudflareChallenge` helper

package.json, packages/templates/templates/camoufox-ts/Dockerfile, packages/templates/templates/camoufox-ts/package.json, renovate.json, test/e2e/camoufox-cloudflare/actor/Dockerfile, test/e2e/camoufox-cloudflare/actor/package.json, yarn.lock
v1.51 apparently broke the camoufox support. we need to pin it in the root package.json too since that is what E2E tests use outside of platform.
```
ERROR Failed to launch browser. Please check the following:
- Check whether the provided executable path "/home/runner/.cache/camoufox/camoufox-bin" is correct.
- Try installing the required dependencies by running `npx playwright install --with-deps` (https://playwright.dev/docs/browsers).
The original error is available in the `cause` property. Below is the error received when trying to launch a browser:
​
Failed to launch browser. Please check the following:
- Check whether the provided executable path "/home/runner/.cache/camoufox/camoufox-bin" is correct.
- Try installing the required dependencies by running `npx playwright install …
```
=> chore: pin playwright to 1.50.1 to fix camoufox template

packages/http-crawler/src/internals/http-crawler.ts, test/core/crawlers/cheerio_crawler.test.ts
Removes the legacy logic for custom handling of the `406` status code. 
Aligns the `HttpCrawler` behavior with other crawlers, e.g.:
```typescript
const crawler = new PlaywrightCrawler({
requestHandler: async ({ page, request }) => {
console.log(request.url);
},
});
await crawler.run(['https://httpbin.org/status/406']);
/// prints https://httpbin.org/status/406
```
Closes #2892
=> fix: treat `406` as other `4xx` status codes in `HttpCrawler`

packages/basic-crawler/src/internals/basic-crawler.ts, packages/browser-crawler/src/internals/browser-crawler.ts, packages/cheerio-crawler/src/internals/cheerio-crawler.ts, packages/core/src/enqueue_links/enqueue_links.ts, packages/http-crawler/src/internals/http-crawler.ts, packages/jsdom-crawler/src/internals/jsdom-crawler.ts, packages/linkedom-crawler/src/internals/linkedom-crawler.ts, packages/utils/src/internals/robots.ts, test/e2e/cheerio-robots-file/actor/.actor/actor.json, test/e2e/cheerio-robots-file/actor/.gitignore, test/e2e/cheerio-robots-file/actor/Dockerfile, test/e2e/cheerio-robots-file/actor/main.js, test/e2e/cheerio-robots-file/actor/package.json, test/e2e/cheerio-robots-file/test.mjs, test/e2e/playwright-robots-file/actor/.actor/actor.json, test/e2e/playwright-robots-file/actor/.gitignore, test/e2e/playwright-robots-file/actor/Dockerfile, test/e2e/playwright-robots-file/actor/main.js, test/e2e/playwright-robots-file/actor/package.json, test/e2e/playwright-robots-file/test.mjs
This PR implements automatic skipping of requests based on the robots.txt file. It works based on a new boolean flag in the crawler options called `respectRobotsTxtFile`.
Checks are implemented in `BasicCrawler._runTaskFunction()`, `enqueueLinks` (the context helper), and `BasicCrawler.addRequests()`, so we ensure disallowed requests are neither processed, nor added to the queue (this only works with the `enqueueLinks` context helper). The robots.txt files are cached based on the URL origin, so we should fetch it only once for each domain (up to 1000 domains, uses LRU cache). We don't use a proxy to fetch the robots.txt file, which should be fine, since the file should be accessible by robots in general.
We might want to enable this by default in the next major.
=> feat: add `respectRobotsTxtFile` crawler option

packages/basic-crawler/src/internals/basic-crawler.ts, packages/browser-crawler/src/internals/browser-crawler.ts, packages/cheerio-crawler/src/internals/cheerio-crawler.ts, packages/core/src/enqueue_links/enqueue_links.ts, packages/jsdom-crawler/src/internals/jsdom-crawler.ts, packages/linkedom-crawler/src/internals/linkedom-crawler.ts, packages/utils/src/internals/robots.ts, packages/utils/src/internals/sitemap.ts, packages/utils/test/robots.test.ts
The old name is still supported as an alias, will be removed in v4.
Related #2910
=> fix: rename `RobotsFile` to `RobotsTxtFile`

packages/core/src/storages/sitemap_request_list.ts
Thanks @barjin for pointing this out
=> chore(hotfix): Fix SitemapRequestList persist state event binding

docs/guides/avoid_blocking_camoufox.ts, packages/templates/templates/camoufox-ts/src/main.ts
Using default Crawlee-issued fingerprints (through the `fingerprint-injector`) with the Camoufox browser can lead to inconsistent browser fingerprints (see e.g. https://github.com/apify/camoufox-js/issues/11).
This PR explicitly disables the default fingerprints in Camoufox examples / templates.
=> fix: disable default fingerprints in the Camoufox template

packages/http-crawler/src/internals/file-download.ts, test/core/crawlers/file_download.test.ts
For proper usage of the streamed response, we often need access to the `content-type` or `content-length` headers. This PR passes the `response` object (containing e.g. headers and status code) to the `streamHandler` context.
=> feat: pass `response` to `FileDownload.streamHandler`

packages/basic-crawler/src/internals/basic-crawler.ts, packages/core/src/crawlers/statistics.ts, test/core/crawlers/statistics.test.ts
Encountered when debugging run with a migration. A few notes to stats in general:
1. The statistics.ts is implemented like a generic tracking tool, but it was ever only used to track request retries and timing, so it would benefit from being tightly coupled with the Request object. So there is potential for bigger rewrite, after my change it is only really tracking time of requests and that doesn't survive migration (not sure if it even useful for anyone). If we store initial time to Request, we can get rid of the Job thing.
2. The 
```
"requestsFinished": 97,
"requestsFailed": 11,
"requestsRetries": 44,
```
is really confusing. `requestsRetries` are not total retries but requests that have at least one retry, those are subset of `requestsFinished` while `requestsFailed` are completely …
=> fix(statistics): track actual request.retryCount in Statistics

packages/core/src/crawlers/crawler_commons.ts, packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts, test/core/crawlers/adaptive_playwright_crawler.test.ts
I noticed that the useState() implementation in adaptive playwright crawler was prone to race conditions. On top of that, during rendering type detections, the HTTP request handler could receive an older copy of the state than what the browser handler was working with. 
This pull request exposes the crawler state as a mutable value, with all the associated risks. The copy for the HTTP request handler is made on demand, during the first useState call in the browser request handler.
=> fix: Fix useState behavior in adaptive crawler

packages/basic-crawler/src/internals/basic-crawler.ts
Improves the option documentation based on [the discussion in Crawlee Python](https://github.com/apify/crawlee-python/issues/1171). Once we reach agreement on the new wording, we should update this in [Crawlee Python too](https://github.com/apify/crawlee-python/blob/9a63edf64be7cb032fe5345701e727c9f0af9f3e/src/crawlee/crawlers/_basic/_basic_crawler.py#L112).
=> docs: improve `maxRequestRetries` documentation

packages/core/src/autoscaling/snapshotter.ts, packages/core/src/events/local_event_manager.ts
When no `memoryMbytes` option is provided, we infer the available memory in the snapshotter. This place was not respecting the `systemInfoV2` option, which this PR resolves.
Closes #2958
=> fix(core): respect `systemInfoV2` in snapshotter

packages/utils/src/internals/social.ts, test/utils/social.test.ts
This extracts all text nodes from a HTML and calls `emailsFromText` on each separately. This is to avoid concacenating texts of adjancent elements, for example:
`<div><a>000 000</a><a>eva@example.com</a></div>`.
`htmlToText` would turn the HTML into `000 000eva@example.com` and we'd end up with an invalid email `000eva@example.com`.
=> fix(social): extract emails from each text node separately

packages/http-crawler/src/internals/http-crawler.ts, packages/impit-client/package.json, packages/impit-client/src/index.ts, test/core/crawlers/http_crawler.test.ts, yarn.lock
Runs the `HttpCrawler` tests with both `HttpClient` implementations (`GotScrapingHttpClient`, `ImpitHttpClient`). 
Improves cookie store integration for `ImpitHttpClient`.
=> fix: enable full cookie support for `ImpitHttpClient`

packages/basic-crawler/src/internals/basic-crawler.ts
Following #2948, `isTaskReadyFunction` can now be overridden by crawler constructor options.
=> docs: `isTaskReadyFunction` can be overridden

packages/basic-crawler/src/internals/basic-crawler.ts, packages/core/src/storages/request_provider.ts, packages/core/src/storages/request_queue_v2.ts, packages/utils/src/index.ts, packages/utils/src/internals/iterables.ts, test/core/crawlers/basic_crawler.test.ts, test/core/enqueue_links/click_elements.test.ts, test/core/enqueue_links/enqueue_links.test.ts, test/utils/iterables.test.ts
- closes #2980
- the Apify client does not accept iterables yet, so the individual "batches" are still stored in memory 
- even considering that, the change should enable reducing memory footprint by passing in an async generator that loads a long list of requests
=> feat: Accept (Async)Iterables in `addRequests` methods

packages/core/src/crawlers/crawler_commons.ts, packages/core/src/enqueue_links/enqueue_links.ts, packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts, test/core/crawlers/adaptive_playwright_crawler.test.ts
=> fix: Fix link filtering in enqueueLinks in AdaptivePlaywrightCrawler

test/e2e/playwright-multi-run/test.mjs
If the `maxRequestsPerCrawl` is not overshot, the total number of results can be equal to `30`.
=> chore(e2e): make `playwright-multi-run` more stable

packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
`AdaptivePlaywrightCrawler` seems to have been omitted from #3026 and #2990. This PR fixes those omissions.
Closes #3039
=> fix: call `onSkippedRequest` for `AdaptivePlaywrightCrawler.enqueueLinks`

packages/basic-crawler/src/internals/basic-crawler.ts, packages/browser-crawler/src/internals/browser-crawler.ts, packages/cheerio-crawler/src/internals/cheerio-crawler.ts, packages/core/src/enqueue_links/enqueue_links.ts, packages/core/src/enqueue_links/shared.ts, packages/core/src/request.ts, packages/jsdom-crawler/src/internals/jsdom-crawler.ts, packages/linkedom-crawler/src/internals/linkedom-crawler.ts, test/core/crawlers/basic_crawler.test.ts, test/core/crawlers/browser_crawler.test.ts, test/core/crawlers/cheerio_crawler.test.ts, test/core/storages/request_queue.test.ts
Adds `BasicCrawlerOptions.maxCrawlDepth` option. Works with `addRequests` and `enqueueLinks` **called from the crawling context** (those have the current request depth bound and can propagate this value to the new requests).
Closes #2633
=> feat: add `maxCrawlDepth` crawler option

packages/http-crawler/src/internals/http-crawler.ts
Enables blocked HTTP status code detection in `HttpCrawler`. This copies the behaviour from `BrowserCrawler` [here](https://github.com/apify/crawlee/blob/f68d2a95d67cc6230122dc1a5226c57ca23d0ae7/packages/browser-crawler/src/internals/browser-crawler.ts#L481-L486).
Closes #3029
=> fix: retry on blocked status codes in `HttpCrawler`

.github/workflows/release.yml
After creating the new version snapshot with `docusaurus version x.y`, we should deploy the docs.
=> chore: don't skip docs build on release

packages/basic-crawler/src/internals/basic-crawler.ts, packages/core/src/storages/dataset.ts, test/core/crawlers/basic_crawler.test.ts
Ports the `collectAllKeys` option from #3007 to the `BasicCrawler.exportData` method. `Dataset.exportTo` and `BasicCrawler.exportData` seem way too similar for this omission to be intentional. If it is so, feel free to close this PR.
=> feat: add `collectAllKeys` option for `BasicCrawler.exportData`

packages/core/src/proxy_configuration.ts, test/core/crawlers/browser_crawler.test.ts
=> fix: `proxyUrls` list can contain `null`

website/src/pages/js.js
The box with "Handy scraping utils" on Crawlee JS homepage (https://crawlee.dev/js) leads to avoid-blocking instead of utils
=> docs: fix `utilities` card link on homepage

packages/browser-pool/src/playwright/playwright-controller.ts, test/core/crawlers/playwright_crawler.test.ts
`launchContext.launchOptions` are not applied with `useIncognitoPages` in `PlaywrightCrawler` because of the split between Browser and BrowserContext in Playwright.
See more details in [the comment](https://github.com/apify/crawlee/issues/3173#issuecomment-3346728227) to #3173 .
Closes #3173
=> fix: correctly apply `launchOptions` with `useIncognitoPages`
