apify/crawlee

- src/autoscaled_pool.js
- test/autoscaled_pool.js
> Adding finishWhenEmpty and maybeRunIntervalMillis opts to autoscaled pool

- CHANGELOG.md
- package.json
- src/actor.js
- src/basic_crawler.js
- src/dataset.js
- src/key_value_store.js
- src/puppeteer.js
- src/puppeteer_crawler.js
- src/puppeteer_pool.js
- src/request_queue.js
- src/utils.js
- test/actor.js
- test/puppeteer.js
- test/puppeteer_crawler.js
- test/request_queue.js
- test/utils.js
> Moving some constants to apify-shared and changing proxy configuration

- CHANGELOG.md
- src/request_queue.js
- test/request_queue.js
> RequestQueue - caching requests locally

- src/puppeteer_pool.js
- test/puppeteer_pool.js
Implements https://github.com/apifytech/apify-js/issues/122
I would like your comments on `_findInstanceByBrowser` return value. The `default case` should never happen, but on the other hand, it feels weird to leave the situation unhandled.
> Add puppeteerPool.retire() function to manually retire browsers

- .eslintrc.json
- README.md
- package.json
- src/key_value_store.js
- src/webdriver.js
- test/autoscaled_pool.js
- test/basic_crawler.js
- test/key_value_store.js
Fixes https://github.com/apifytech/apify-js/issues/123
> Fix BUG: Apify.setValue() throws on keys that include slashes

- src/puppeteer_pool.js
Fixes https://github.com/apifytech/apify-js/issues/72
> Add explicit termination of Puppeteer subprocesses

- src/basic_crawler.js
- src/request_queue.js
- test/request_queue.js
…ue yet causing it to stuck forever
> Request queue fix + missing await in BasicCrawler as bonus

- CHANGELOG.md
- docs/api/Apify.md
- docs/api/RequestQueue.md
- docs/api/puppeteer.md
- docs/examples/Screenshots.md
- docs/typedefs/QueueOperationInfo.md
- examples/screenshots.js
- src/pseudo_url.js
- src/puppeteer.js
- src/puppeteer_utils.js
- src/request.js
- src/request_queue.js
- test/request_queue.js
- website/core/Footer.js
- website/i18n/en.json
- website/pages/en/index.js
- website/sidebars.json
Merge after https://github.com/apifytech/apify-js/pull/213
> Renamed RequestOperationInfo to QueueOperationInfo

- CHANGELOG.md
- docs/api/Apify.md
- docs/examples/Screenshots.md
- examples/screenshots.js
- src/pseudo_url.js
- src/puppeteer.js
- src/request.js
- src/request_queue.js
- test/request_queue.js
- website/core/Footer.js
- website/pages/en/index.js
Only merge after https://github.com/apifytech/apify-js/pull/212
> Added RequestOperationInfo.request field

- CHANGELOG.md
- src/autoscaling/autoscaled_pool.js
- test/autoscaling/autoscaled_pool.js
Tackles https://github.com/apifytech/apify-js/issues/186
Perhaps a version bump is necessary?
(also fixes unrelated flaky test)
> AutoscaledPool reject on isFinishedFunction and isTaskReadyFunction fails

- src/cheerio_crawler.js
- src/index.js
- test/cheerio_crawler.js
- test/data/sample.html
Tackles: https://github.com/apifytech/apify-js/issues/252
> Add compression / decompression capability to CheerioCrawler

- docs/api/PseudoUrl.md
- docs/api/utils.md
- src/enqueue_links.js
- src/pseudo_url.js
- test/enqueue_links.js
- test/pseudo_url.js
- Make `PseudoUrl` matching case insensitive
- Enable construction of `PseudoUrl` with `RegExp`
- Ensure this works in `enqueueLinks`
> Some PseudoURL updates

- CHANGELOG.md
- src/autoscaling/snapshotter.js
- test/autoscaling/snapshotter.js
Added logging to critical memory overload.
> Created critical memory overload log.

- src/key_value_store.js
- test/key_value_store.js
This fixes inconsistency between `KeyValueStoreLocal.forEachKey` and `KeyValueStore.forEachKey`.
> Fixed forEachKey incosistency

- docs/guides/data_storage.md
- docs/guides/getting_started.md
- examples/screenshots.js
- package.json
- src/actor.js
- src/index.js
- src/key_value_store.js
- src/utils.js
- test/_helper.js
- test/actor.js
- test/basic_crawler.js
- test/cheerio_crawler.js
- test/data/html_to_text_test.txt
- test/dataset.js
- test/key_value_store.js
- test/puppeteer_crawler.js
- test/puppeteer_pool.js
- test/puppeteer_utils.js
- test/request_list.js
- test/request_queue.js
- test/utils.js
- test/utils_social.js
* Improving getEnv()
* Adding getInput()
* Removing chaiAsPromised initialization from tests, moving to _helper.js
> Apify.getInput()

- src/basic_crawler.js
Just adding request ID to error log
> Adding requestId to logs

- CHANGELOG.md
- MIGRATIONS.md
- README.md
- docs/guides/getting_started.md
- docs/guides/getting_started_quick.md
- docs/readme/introduction.md
- docs/readme/overview.md
- test/webdriver.js
- website/core/Footer.js
- website/i18n/en.json
- website/sidebars.json
@mnmkng please review the tutorial whether it still makes sense
> Replaced www.apify.com to apify.com in docs

- docs/api/CheerioCrawler.md
- src/cheerio_crawler.js
- test/cheerio_crawler.js
I have added a feature preview. I am looking forward to the feedback. I will add tests after the feedback process.
> BeforeRequestFunction

- CHANGELOG.md
- src/basic_crawler.js
- src/puppeteer_pool.js
- test/puppeteer_pool.js
Only merge this after new version of Puppeteer lands
> [WIP] Feature/recycle disk cache

- CHANGELOG.md
- src/autoscaling/snapshotter.js
- src/autoscaling/system_status.js
- test/autoscaling/snapshotter.js
Title says it all.
Needs https://github.com/apifytech/apify-client-js/pull/109 first.
> Throttle API by AutoscaledPool on 2nd retry, not immediately

- src/live_view/index.html
- src/live_view/live_view_server.js
- src/puppeteer_pool.js
- test/live_view/live_view_server.js
This PR improves the live view UI and enables other UX improvements, such as making the screenshots only once in 2 secs, timing out after 3 secs to prevent hanging, and most importantly adding the ability to start making snapshots immediately after the LiveView tab is open on Platform, without having to click the enable button.
> Live view UI and UX improvements

- src/cheerio_crawler.js
`prepareRequestFunction` returns `Request`, which is then used to make the HTTP request. The trouble is, this is the only place where it's used, so all other operations in SDK are done with the original `Request` object. This creates inconsistency in error handling, request queue and so on.
This PR changes `prepareRequestFunction` invocation and docs to make it clear that the modifications need to be done in place by modifying the `Request` directly. Any object returned from the function will be discarded to prevent inconsistencies.
> Make prepareRequestFunction consistent in CheerioCrawler

- package.json
- src/actor.js
- src/dataset.js
- src/key_value_store.js
- src/request_queue.js
- src/utils.js
Just a chore PR that removes Bluebird and rewrites logic to native `async` where needed.
> Get rid of bluebird dependency

- docs/api/CheerioCrawler.md
- docs/api/Request.md
- package.json
- src/cheerio_crawler.js
- test/cheerio_crawler.js
WIP:
- Bluebird removal needs to be merged first.
- Decide if we should get rid of full HTML entirely.
This PR attempts to fix high memory usage by streaming the HTML parsing in Cheerio.
Seems to improve the situation, but does not resolve the issue completely.
> [WIP] Streaming Cheerio

- CHANGELOG.md
- docs/examples/SynchronousRun.md
- docs/guides/getting_started.md
- docs/guides/what_is_an_actor.md
- src/autoscaling/snapshotter.js
- test/autoscaling/snapshotter.js
Most importantly, it moves away from "in container" memory measurements to Docker provided stats when running on platform.
> Use new systemInfo event in Snapshotter

- CHANGELOG.md
- src/puppeteer.js
- src/puppeteer_pool.js
- test/puppeteer_pool.js
I don't think it's necessary to mention in the docs anywhere, since from the point of our API, it's internal.
> Use pipe instead of web sockets

- src/utils.js
Changed docs to match code instead of vice-versa.
> fixed ectractUrls docs

- CHANGELOG.md
- docs/api/PuppeteerCrawler.md
- src/crawlers/puppeteer_crawler.js
https://github.com/apifytech/apify-js/issues/430
> Add gotoTimeoutSecs and remove deprecated fields

- CHANGELOG.md
- docs/api/PuppeteerPool.md
- src/puppeteer_pool.js
- test/puppeteer_pool.js
We kinda missed this feature and it was a tiny change.
> Add useIncognitoPages to PuppeteerPool

- examples/forms.js
> add example for filling a form

- CHANGELOG.md
- src/request_list.js
- test/request_list.js
> RequestList: Persist downloaded requests from requestsFromUrl

- CHANGELOG.md
- src/request_queue.js
> Fix RequestQueueLocal race condition

- CHANGELOG.md
- package.json
- src/crawlers/cheerio_crawler.js
- src/key_value_store.js
- src/utils.js
- test/utils.js
> Fixed parsing for bad content-type header in CheerionCrawler #498

- docs/api/Session.md
- docs/api/SessionPool.md
- src/index.js
- src/session_pool/session.js
- src/session_pool/session_pool.js
- test/session_pool/session.test.js
- test/session_pool/session_pool.test.js
Changed session.id to match the proxy session regex.  closes #515 and #516
> improved session pool docs and parameters.

- docs/guides/getting_started.md
Fixed formatting + example for transformRequestFunction
> Improve docs [skip ci]

- CHANGELOG.md
- README.md
- docs/api/Apify.md
- docs/api/CheerioCrawler.md
- docs/api/Dataset.md
- docs/api/KeyValueStore.md
- docs/api/RequestQueue.md
- docs/examples/PuppeteerWithProxy.md
- docs/examples/Screenshots.md
- docs/guides/data_storage.md
- docs/guides/environment_variables.md
- docs/guides/getting_started.md
- docs/guides/getting_started_quick.md
- docs/guides/what_is_an_actor.md
- docs/readme/introduction.md
- docs/typedefs/ActorRun.md
- docs/typedefs/LaunchPuppeteerOptions.md
- examples/puppeteer_with_proxy.js
- examples/screenshots.js
- src/actor.js
- src/crawlers/cheerio_crawler.js
- src/dataset.js
- src/key_value_store.js
- src/puppeteer.js
- src/request_queue.js
- src/utils.js
Duplicate of #537. Closes #537.
> Apienx feature/ap 1523 fix most sdk links

- src/puppeteer_pool.js
- test/puppeteer_pool.test.js
Moved the active pages decreasing into page.close event which is fired once the page is closed or dies.
> PuppeteerPool - Fixed the activePages counting.

- CHANGELOG.md
- package.json
- src/actor.js
- src/index.js
> Move logging from require time to Apify.main execution

- docs/api/CheerioCrawler.md
- docs/typedefs/CheerioCrawlerOptions.md
- src/crawlers/cheerio_crawler.js
- types/crawlers/cheerio_crawler.d.ts
Please can you guys review if the described logic is correct, and also if the JSDocs links are right? I'm not sure how exactly they work...
> Better docs for CheerioCrawler's parsing behavior

- src/crawlers/cheerio_crawler.js
- src/crawlers/crawler_extension.js
- test/crawlers/cheerio_crawler.test.js
- test/crawlers/crawler_extension.test.js
Not sure if I did not end up going the wrong path. However, this logic is easily pluggable to the other crawlers. Also, it could possibly merge the nested object configurations such as the `sessionPoolOptions`, `autoscaledPoolOptions`...
> Created crawler use proposal in CheerioCrawler class.

- CHANGELOG.md
- src/actor.js
- src/crawlers/cheerio_crawler.js
- src/utils.js
I tried to avoid any breaking changes so at some places the excision is not perfect. Gets the job done to be able to release it in latest as soon as this gets approved though.
Added changelog updates we were missing.
> Excise waitForRunToFinish from Apify.call and export it

- src/request_list.js
Tiny update to the docs after a user on support got duplicates because of non-persisted RequestList.
> Be more explicit about state in RequestList docs

- website/core/Footer.js
- website/i18n/en.json
- website/pages/en/index.js
- website/sidebars.json
- website/siteConfig.js
- website/tools/build_docs.js
> Add examples to sidebar and some other stuff

- docs/guides/proxy_management.md
- src/crawlers/cheerio_crawler.js
- src/proxy_configuration.js
- test/proxy_configuration.test.js
> Add sessionId length validation

- .travis.yml
- package.json
- src/crawlers/cheerio_crawler.js
- src/serialization.js
- test/serialization.test.js
- test/typescript/crawlers/cheerio_crawler.test.ts
Closes #788 and puts us back in the game.
> Fix Node 14 and add it to Travis pipeline 

- CHANGELOG.md
- package.json
- src/crawlers/puppeteer_crawler.js
- test/crawlers/cheerio_crawler.test.js
- test/crawlers/puppeteer_crawler.test.js
Not sure how we missed this. 🤦
> Fix session management in PuppeteerCrawler

- src/session_pool/session.js
- test/session_pool/session.test.js
> Fixed retiring of session, when get session is not used per request.

- src/stealth/hiding_tricks.js
- src/stealth/stealth.js
- test/stealth/stealth.test.js
- Fixed the language setting
- Added debugging to stealth in order to identify the performance issues
> Hotfix stealth

- src/crawlers/cheerio_crawler.js
- test/crawlers/cheerio_crawler.test.js
- Added `postResponseFunction` to available setting custom properties of response before parsing
- Separation the parsing part of the `_requestFunction` for `_parseResponse` function
> CheerioCrawler: postResponseFunction

- src/crawlers/cheerio_crawler.js
- test/crawlers/cheerio_crawler.test.js
Added `text/xml` to default mime types
> CheerioCrawler: text/xml content type works

- src/utils_request.js
- test/utils_request.test.js
> fixes HTTP2 in requestAsBrowser

- .babelrc
- .eslintrc.json
- package.json
- src/crawlers/basic_crawler.js
- src/crawlers/cheerio_crawler.js
- src/crawlers/puppeteer_crawler.js
- test/crawlers/cheerio_crawler.test.js
- test/crawlers/puppeteer_crawler.test.js
- test/stealth/stealth.test.js
> Refactor Crawlers to inherit from BasicCrawler

- src/proxy_configuration.js
Creating PR, because I didn't know if I commit this directly to master
> Improved ProxyConfiguration.newUrl() docs

- src/actor.js
Closes https://github.com/apify/apify-js/issues/998
> fix: error when Apify.call does not return OUTPUT

- src/autoscaling/autoscaled_pool.js
We're seeing actors stuck at 0 concurrency for no apparent reason. This logging could help narrow down the problem.
> chore: add perf logging to autoscaledpool

- CHANGELOG.md
- package.json
- src/utils_request.js
- test/utils_request.test.js
@B4nan please release the SDK v1.2.1 after checking this, I'll be driving out of Prague.
Closes: #1028
> fix: requestAsBrowser legacy options json/payload

- docs/guides/apify_platform.md
- docs/guides/getting_started.md
- docs/guides/quick_start.md
Multiple text changes in three files. Please double check before merging if possible and ask me if any questions. Thanks!
> docs: fix copywriting

- src/session_pool/session.js
- src/session_pool/session_pool.js
- test/session_pool/session_pool.test.js
> Restored sessions use current pool's maxUsageCount

- CHANGELOG.md
- src/browser_launchers/browser_launcher.js
- test/browser_launchers/playwright_launcher.test.js
- test/browser_launchers/puppeteer_launcher.test.js
- test/crawlers/cheerio_crawler.test.js
Closes #1063 . Also fixes some flaky tests, updates changelog...
> fix: proxyUrl without port throwing on browser launch

- CHANGELOG.md
- package.json
- src/utils_request.js
- test/utils_request.test.js
- website/versioned_docs/version-1.3.1/api/Apify.md
- website/versioned_docs/version-1.3.1/api/BasicCrawler.md
- website/versioned_docs/version-1.3.1/api/CheerioCrawler.md
- website/versioned_docs/version-1.3.1/api/Configuration.md
- website/versioned_docs/version-1.3.1/guides/apify_platform.md
- website/versioned_docs/version-1.3.1/guides/getting_started.md
- website/versioned_docs/version-1.3.1/guides/quick_start.md
- website/versioned_docs/version-1.3.1/typedefs/AutoscaledPoolOptions.md
- website/versioned_docs/version-1.3.1/typedefs/CheerioCrawlerOptions.md
- website/versioned_docs/version-1.3.1/typedefs/CheerioHandlePageInputs.md
- website/versioned_docs/version-1.3.1/typedefs/LoggerOptions.md
- website/versioned_docs/version-1.3.1/typedefs/PlaywrightCrawlerOptions.md
- website/versioned_docs/version-1.3.1/typedefs/PuppeteerCrawlerOptions.md
- website/versioned_docs/version-1.3.1/typedefs/RequestAsBrowserOptions.md
- website/versioned_sidebars/version-1.3.1-sidebars.json
> fix: headerGeneratorOptions not passed to requestAsBrowser

- CHANGELOG.md
- src/crawlers/basic_crawler.js
- test/crawlers/basic_crawler.test.js
> fix: limit `handleRequestTimeoutMillis` to max valid value

- CHANGELOG.md
- package.json
- src/crawlers/cheerio_crawler.js
- src/utils_request.js
lmk if this is good, I'll bump `got-scraping` to `3.1.0` and merge this PR afterwards
> feat: use session token with got-scraping

- CHANGELOG.md
- src/configuration.js
- test/apify.test.js
> fix: casting of int/bool environment variables (e.g. `APIFY_LOCAL_STORAGE_ENABLE_WAL_MODE`)

- src/puppeteer_utils.js
- test/puppeteer_utils.test.js
> feat: add a breaking callback to `infiniteScroll`

- src/request_list.js
- test/request_list.test.js
> fix: automatically convert gdoc share urls to csv download ones in request list

- src/utils.js
- test/utils.test.js
> feat: add support for cgroups V2 to utils.getMemoryInfo

- src/playwright_utils.js
- src/puppeteer_request_interception.js
> fix: catch errors inside request interceptors

- package.json
- src/request_list.js
- src/utils.js
- test/request_list.test.js
> fix: automatically convert google spreadsheet URLs to CSV exports

- src/crawlers/browser_crawler.js
One of the most annoying bugs I've dealt with.
> fix: proxy per page broke session fetching

- package.json
- renovate.json
- src/utils.js
> fix: use correct apify-client instance for snapshotting

- CHANGELOG.md
- src/crawlers/statistics.js
> feat: add `keyValueStore` option to `Statistics` class

- package.json
> Revert "chore(deps): update dependency puppeteer to v14"

- test/crawlers/browser_crawler.test.js
Fix proxyUrl related test after failing after https://github.com/apify/browser-pool/pull/75
> test: fix failing tests

- CHANGELOG.md
- docs/upgrading/upgrading_v3.md
- test/e2e/tools.mjs
Plus few more nits.
Also related to https://github.com/apify/apify-sdk-js/pull/5
> docs: update Actor SDK with Apify SDK

- packages/memory-storage/src/memory-storage.ts
- packages/memory-storage/src/workers/file-storage-worker-emulator.ts
- packages/memory-storage/src/workers/file-storage-worker.ts
- packages/memory-storage/src/workers/instance.ts
- packages/memory-storage/src/workers/worker-utils.ts
- packages/types/src/storages.ts
Ensures the files are actually saved to the disk, as well as speeds up deletion of old files
> fix: improve file saving on memory storage

- docs/guides/apify_platform.mdx
* Updated `Storages` part
* You/We stuff
* Few more nits
> docs: update apify_platform guide

- .eslintrc.json
- package.json
- packages/browser-crawler/src/internals/browser-crawler.ts
- packages/browser-crawler/src/internals/browser-launcher.ts
- packages/browser-pool/copy-definitions.mjs
- packages/browser-pool/src/abstract-classes/browser-plugin.ts
- packages/browser-pool/src/browser-pool.ts
- packages/browser-pool/src/container-proxy-server.ts
- packages/browser-pool/src/launch-context.ts
- packages/browser-pool/src/playwright/playwright-controller.ts
- packages/browser-pool/src/playwright/playwright-plugin.ts
- packages/browser-pool/src/puppeteer/puppeteer-controller.ts
- packages/browser-pool/tab-as-a-container/background.js
- packages/browser-pool/tab-as-a-container/content.js
- packages/browser-pool/tab-as-a-container/manifest.json
- packages/playwright-crawler/src/internals/playwright-crawler.ts
- packages/playwright-crawler/src/internals/playwright-launcher.ts
- test/browser-pool/browser-plugins/plugins.test.ts
- test/e2e/playwright-chromium-experimental-containers/actor/.gitignore
- test/e2e/playwright-chromium-experimental-containers/actor/Dockerfile
- test/e2e/playwright-chromium-experimental-containers/actor/apify.json
- test/e2e/playwright-chromium-experimental-containers/actor/main.js
- test/e2e/playwright-chromium-experimental-containers/actor/package.json
- test/e2e/playwright-chromium-experimental-containers/test.mjs
No tests, this needs to be tested manually with high concurrency.
> ❕ **Info**
>  Watch out for `Request without proxy` in logs and other warnings like:
```
Request to https://www.amazon.com/favicon.ico was through 127.0.0.1 instead of 127.0.0.2
```
> **Note**
> Do not use Playwright's cookie API since it doesn't strip container prefixes. Use Session API instead.
> **Warning**
> **Highly experimental.** There's race condition when sending requests through selected proxies (since it needs to change global proxy when there's a new request). The race condition is due to how the networking stack was implemented in Chromium and is unfixable. When testing Amazon, I noticed this only for resources such as CSS / JS / Image so let's hope this is not breaking. If it is then we'll have to either …
> feat: tab as a container + proxy per page

- docs/guides/apify_platform.mdx
- packages/core/src/configuration.ts
- add descriptions to `ConfigurationOptions` - would really appreciate a fresh look here + double check the default values. etc
- Update the apify-platfrom guide (reword a bit the note about actor init/exit / main).
> docs: update ConfigurationOptions description + more

- packages/basic-crawler/src/internals/basic-crawler.ts
- test/core/crawlers/basic_crawler.test.ts
> fix: sendRequest types

- packages/memory-storage/src/memory-storage.ts
~~Should make #1435 less probable (or outright fix it), however, as I have been unable to consistently replicate the issue mentioned (i can replicate it ~ once every 10-15 tries), this is still in the air~~
Fixes #1435
> fix: key value stores emitting an error when multiple write promises ran in parallel 

- packages/browser-pool/tab-as-a-container/background.js
programatically -> programmatically
> chore: fix typo in background.js

- packages/core/src/enqueue_links/enqueue_links.ts
- packages/core/src/enqueue_links/shared.ts
- packages/core/test/enqueue_links/user-provided-patterns-with-enqueue-strategy.test.ts
> fix(enqueueLinks): ensure the enqueue strategy is respected alongside user patterns

- packages/core/src/enqueue_links/shared.ts
> fix(enqueueLinks): prevent useless request creations when filtering by user patterns

- docs/examples/skip-navigation.ts
> docs: fix `skip-navigation` example

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Updated on GitHub directly so it created 3 commits, feel free to squash them. Also perhaps check the language with content team.
> chore: Fix/typo & rephrasing of issue templates

- docs/examples/playwright_crawler_firefox.mdx
- docs/examples/playwright_crawler_firefox.ts
- website/versioned_docs/version-3.0/examples/playwright_crawler_firefox.mdx
- website/versioned_docs/version-3.0/examples/playwright_crawler_firefox.ts
I guess it should be enough.
p.s.: wrong commit message :/
> docs: add playwright + firefox example

- packages/core/src/except.ts
- packages/core/src/router.ts
- test/core/router.test.ts
Fixes #1477
Simplified playground to see how it works:
https://www.typescriptlang.org/play?#code/PTAEGUHkFUCUGECiAoZAXAngBwKangPYB2aOAHmgDwAiAhmrQHygC8oA3sqN6ACb20AXKDoMA3Fx4AvAPzCA5FPkSAvhOQBjADa0AzrtCwCAV1IAnSvFDlSRXgcIkblY0QDWRAgHcijZpx5QWl5eAAlaOy0cCwBNVnwAbXl+BnkAXUYACgALCN4os2FMjWJSCmFIAFsASyp4ABpQZIF5ZgAyDhShUBiVAEpWZgA3AmreAfYVZCnkEFAAFWy8NDMMUAAjHC1vPgIcXSJ5NFAvAjM3DZwNWmNdPHnwXf3D45u0Akr6auutLTXqogAM2ioEwuAMWmqbmWuTQADpZmBtHoDEZTNFLNYKDg7A5Ss5RExGoT-IjAkEQuFIhi4mwSTk8gUiiUnOVQFVapZGs1Uu1OgJhL0BixhqNxhwpnMZnN5ohwPNUCzdMdaaAiDgvIYTOZKOwusJ2ICCARhERjJVNmYVI0pMJXLwcICATheCosn11DE4cEwoyMYbjcJlWYAQBzN2ZYr4ijC0mBFlleFdOFGggSePR+FSVQe1Ben1U-LRSMJmyxjiSbilihw5Op9M8atZnNiIA
> feat(router): add userdata generic to addHandler

- packages/http-crawler/src/internals/http-crawler.ts
- test/core/crawlers/http_crawler.test.ts
> fix(http-crawler): do not hang on POST without payload

- packages/playwright-crawler/src/internals/utils/playwright-utils.ts
- test/core/playwright_utils.test.ts
> feat: add `utils.playwright.saveSnapshot`

- packages/playwright-crawler/src/internals/utils/playwright-utils.ts
> feat: add `utils.playwright.compileScript`

- packages/core/src/session_pool/session_pool.ts
The flow is really weird and always freaks me out when I'm trying to understand it. I will file issue with improvement proposal.
> docs: explain session pool allocation flow

- .github/workflows/release-next.yml
Forgot to add this step in the @next workflow but its there in the actual release one... wooops
> chore: fix missing step

- packages/cli/src/commands/CreateProjectCommand.ts
> fix: add retry attempts to methods in CLI

- packages/browser-pool/src/playwright/playwright-controller.ts
- packages/browser-pool/src/playwright/playwright-plugin.ts
- packages/browser-pool/src/utils.ts
Fixes https://github.com/apify/crawlee/issues/1610
Closes #1629
> fix: type errors when `playwright` is not installed

- package-lock.json
- package.json
- packages/browser-pool/package.json
- packages/crawlee/package.json
- packages/puppeteer-crawler/package.json
- test/e2e/cheerio-enqueue-links/test.mjs
- test/e2e/puppeteer-enqueue-links/test.mjs
> fix: upgrade to puppeteer@19.2.0

- docs/guides/typescript_project.mdx
Correct install commands with `npm`.
Add missing instructions to install `@apify/tsconfig`
> docs: improve TS project guide

- packages/memory-storage/src/resource-clients/dataset.ts
- packages/memory-storage/src/resource-clients/key-value-store.ts
- packages/memory-storage/src/resource-clients/request-queue.ts
- test/shared/MemoryStorageEmulator.ts
- test/shared/StorageEmulator.ts
This will need to be applied to sdk too
> chore: do not write files to disk when running tests

- packages/browser-crawler/src/internals/browser-crawler.ts
- test/core/crawlers/browser_crawler.test.ts
Inheritance, man...
fixes #1641
> fix: requestHandlerTimeout timing

- packages/core/src/errors.ts
> docs: fix RetryRequestError() description

- packages/basic-crawler/src/internals/basic-crawler.ts
- test/core/crawlers/basic_crawler.test.ts
- test/core/crawlers/puppeteer_crawler.test.ts
POC-ish as of now. Doesn't properly work in during development (`crawlee` needs to be loaded from `node_modules`). 
Ideas welcome!
> feat: always show error origin if inside the userland

- packages/core/src/enqueue_links/enqueue_links.ts
@mnmkng would love a review for the message thrown as maybe you have better wording for it
> chore: throw different error if user accidentally imports enqueueLinks

- test/e2e/cheerio-default/actor/main.js
- test/e2e/cheerio-default/test.mjs
Makes the `cheerio-default` e2e test in line with the `cheerio-default-ts` test.
> test: cheerio-default e2e test

- packages/basic-crawler/src/internals/basic-crawler.ts
- test/e2e/session-rotation/actor/.gitignore
- test/e2e/session-rotation/actor/Dockerfile
- test/e2e/session-rotation/actor/apify.json
- test/e2e/session-rotation/actor/main.js
- test/e2e/session-rotation/actor/package.json
- test/e2e/session-rotation/test.mjs
fixes #1635 
Caused by [this](https://github.com/apify/crawlee/blob/5ff04faa85c3a6b6f02cd58a91b46b80610d8ae6/packages/browser-crawler/src/internals/browser-crawler.ts#L524). Oh, don't we all love random modifications to passed parameters...
> fix: session.markBad() on requestHandler error

- packages/basic-crawler/src/internals/basic-crawler.ts
Since we now have request queue integrated into the crawler and request list is almost obsolete, I figured this would sound better.
> chore: improve log message

- package-lock.json
- package.json
- packages/browser-pool/package.json
- packages/crawlee/package.json
- packages/playwright-crawler/package.json
- test/e2e/playwright-chromium-experimental-containers/actor/main.js
> fix: update playwright to 1.29.2 and make peer dep. less strict

- packages/memory-storage/src/cache-helpers.ts
> fix(memory-storage): dont fail when storage already purged

- packages/memory-storage/src/resource-clients/request-queue.ts
Critical mistake caught by @fnesveda 😓
> fix(MemoryStorage): request queues saved in the wrong place

- packages/memory-storage/package.json
- packages/memory-storage/src/fs/request-queue/fs.ts
- packages/memory-storage/src/workers/worker-utils.ts
- yarn.lock
Closes #1792 🤞 
Running E2E as well to see if it worked
> fix(MemoryStorage): request queues race conditions causing crashes

- packages/cheerio-crawler/src/internals/cheerio-crawler.ts
- packages/cheerio-crawler/test/xml.test.ts
- test/shared/_helper.ts
- test/shared/data/complex.xml
> fix(CheerioCrawler): pass ixXml down to response parser

- packages/memory-storage/src/memory-storage.ts
> chore(MemoryStorage): always resolve to a new path when batchRemoveFiles is called

- packages/core/package.json
- packages/core/src/storages/storage_manager.ts
- yarn.lock
> fix(Storage): queue up opening storages to prevent issues in concurrent calls

- packages/memory-storage/src/fs/dataset/fs.ts
- packages/memory-storage/src/fs/key-value-store/fs.ts
- packages/memory-storage/src/fs/request-queue/fs.ts
Closes #1847
Closes #1853 
(hopefully once and for all 😓)
> chore: queue up all fs actions in memory storage

- packages/basic-crawler/src/internals/basic-crawler.ts
- packages/core/src/session_pool/session_pool.ts
https://apifier.slack.com/archives/CD0SF6KD4/p1682510708662429
> fix: respect config object when creating `SessionPool`

- .eslintrc.json
- packages/browser-crawler/src/internals/browser-crawler.ts
- packages/browser-pool/src/browser-pool.ts
- packages/browser-pool/src/utils.ts
- packages/http-crawler/src/internals/http-crawler.ts
To avoid inter-human communication :D
> chore: ESLint comma dangle

- website/src/pages/index.js
> docs: fix emoji rendering on windows

- packages/memory-storage/src/resource-clients/request-queue.ts
- packages/types/src/storages.ts
- test/core/storages/request_queue.test.ts
Adds support for RQv2 locking methods to `MemoryStorage`.
Related to #1365
> feat: RQv2 memory storage support

- packages/http-crawler/package.json
- packages/http-crawler/src/internals/http-crawler.ts
- packages/jsdom-crawler/src/internals/jsdom-crawler.ts
- test/core/crawlers/http_crawler.test.ts
- yarn.lock
As discussed in https://github.com/apify/crawlee/pull/1890
> feat(HttpCrawler): add `parseWithCheerio` helper to `HttpCrawler`

- .github/workflows/test-ci.yml
- packages/basic-crawler/src/internals/basic-crawler.ts
Closes https://github.com/apify-projects/store-website-content-crawler/issues/85
> fix: set status message every 5 seconds and log it via debug level

- .github/workflows/release.yml
I forgot to commit this file in the previous PR.
> chore: update more GitHub workflow secrets

- docs/examples/tsconfig.json
- jest.config.js
- packages/core/README.md
- packages/linkedom-crawler/.npmignore
- packages/linkedom-crawler/README.md
- packages/linkedom-crawler/package.json
- packages/linkedom-crawler/src/index.ts
- packages/linkedom-crawler/src/internals/linkedom-crawler.ts
- packages/linkedom-crawler/tsconfig.build.json
- packages/linkedom-crawler/tsconfig.json
- test/e2e/linkedom-default-ts/actor/.actor/actor.json
- test/e2e/linkedom-default-ts/actor/.gitignore
- test/e2e/linkedom-default-ts/actor/Dockerfile
- test/e2e/linkedom-default-ts/actor/main.ts
- test/e2e/linkedom-default-ts/actor/package.json
- test/e2e/linkedom-default-ts/actor/tsconfig.json
- test/e2e/linkedom-default-ts/test.mjs
- tsconfig.json
- yarn.lock
The clean approach of https://github.com/apify/crawlee/pull/1879
as discussed https://github.com/apify/crawlee/pull/1890#issuecomment-1533271694
2023-05-09 16:05 Rebased
> feat: add LinkeDOMCrawler

- packages/jsdom-crawler/src/internals/jsdom-crawler.ts
- packages/linkedom-crawler/src/internals/linkedom-crawler.ts
- test/e2e/jsdom-default-ts/actor/main.ts
- test/e2e/linkedom-default-ts/actor/main.ts
> feat(jsdom,linkedom): Expose document to crawler router context

- packages/http-crawler/src/internals/http-crawler.ts
- test/core/crawlers/cheerio_crawler.test.ts
- test/core/crawlers/http_crawler.test.ts
This commit introduces two new optional properties to `CheerioCrawler` and `HttpCrawler`, allowing for finer control over how HTTP error status codes are handled:
1. `ignoreHttpErrorStatusCodes`: An array of HTTP response status codes that should be excluded from being considered as errors. By default, error consideration is triggered for status codes >= 500.
2. `additionalHttpErrorStatusCodes`: An array of extra HTTP response status codes that should be treated as errors. By default, error consideration is triggered for status codes >= 500.
These options provide flexibility in specifying which HTTP response codes should be treated as errors and ignored during the crawling process.
Closes #1711
> feat: Add options for custom HTTP error status codes

- packages/basic-crawler/src/internals/basic-crawler.ts
- packages/core/src/session_pool/session_pool.ts
> fix: session pool leaks memory on multiple crawler runs

- packages/cli/src/commands/InstallPlaywrightBrowsersCommand.ts
- packages/cli/src/index.ts
- packages/templates/templates/playwright-js/package.json
- packages/templates/templates/playwright-ts/package.json
Needs https://github.com/apify/apify-actor-docker/pull/111
> fix(templates): install browsers on postinstall for playwright

- packages/basic-crawler/src/internals/basic-crawler.ts
Recently we saw an actor being stuck after it finished. It might be coming from the status message calls and the exponential backoff behind the API calls. This makes sure the status message API call won't take too long.
> fix: ensure the status message cannot stuck the crawler

- packages/memory-storage/src/cache-helpers.ts
- packages/memory-storage/test/request-queue/ignore-non-json-files.test.ts
> fix(MemoryStorage): ignore invalid files for request queues

- test/e2e/puppeteer-store-pagination-jquery/actor/main.js
- test/e2e/puppeteer-store-pagination-jquery/test.mjs
- test/e2e/puppeteer-store-pagination/actor/main.js
- test/e2e/puppeteer-store-pagination/test.mjs
This is a stop gap till I finish rewriting the introduction guide and also the tests related to it
> chore: make e2e pass again

- packages/core/src/session_pool/session.ts
- packages/http-crawler/src/internals/http-crawler.ts
- test/core/crawlers/http_crawler.test.ts
> fix: retry incorrect Content-Type when response has blocked status code

- packages/core/src/storages/key_value_store.ts
This was painful to discover the hard way :(
Code to test this:
```js
const store = await Actor.openKeyValueStore("test", { forceCloud: true });
const key = "something";
const res = await Promise.all([
store.getAutoSavedValue(key, { foo: [] }),
new Promise((r) => setTimeout(r, Math.random() * 1000)).then(() =>
store.getAutoSavedValue(key, { foo: [] })
),
]);
res[0].foo.push("test");
console.log(res);
```
Run this a few times and at some point you will get two different values in the console.log. (Note that it's using `forceCloud` to make `this.GetValue()` run for a little longer.)
> fix: prevent race condition in KeyValueStore.getAutoSavedValue()

- package.json
- packages/basic-crawler/package.json
- packages/browser-crawler/package.json
- packages/browser-pool/package.json
- packages/cheerio-crawler/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/crawlee/package.json
- packages/http-crawler/package.json
- packages/jsdom-crawler/package.json
- packages/linkedom-crawler/package.json
- packages/memory-storage/package.json
- packages/playwright-crawler/package.json
- packages/puppeteer-crawler/package.json
- packages/templates/package.json
- packages/templates/templates/cheerio-ts/package.json
- packages/templates/templates/getting-started-ts/package.json
- packages/templates/templates/playwright-ts/package.json
- packages/templates/templates/puppeteer-ts/package.json
- packages/types/package.json
- packages/utils/package.json
- yarn.lock
> chore: move from ts-node to tsx

- packages/browser-pool/src/fingerprinting/hooks.ts
- packages/browser-pool/src/utils.ts
Related to #2164 Not really sure how to achieve correct typing
> fix(browser-pool): respect user options before assigning fingerpints

- packages/core/src/enqueue_links/shared.ts
- test/core/enqueue_links/enqueue_links.test.ts
> fix: filter out empty globs

- packages/core/package.json
- packages/core/src/session_pool/session_pool.ts
- yarn.lock
> fix: make SessionPool queue up getSession calls to prevent overruns

- docs/examples/crawl_sitemap.mdx
- docs/examples/crawl_sitemap_cheerio.ts
- docs/examples/crawl_sitemap_playwright.ts
- docs/examples/crawl_sitemap_puppeteer.ts
- package.json
- packages/utils/package.json
- packages/utils/src/index.ts
- packages/utils/src/internals/robots.ts
- packages/utils/src/internals/sitemap.ts
- packages/utils/test/robots.test.ts
- packages/utils/test/sitemap.test.ts
- packages/utils/tsconfig.build.json
- yarn.lock
> feat: robots.txt and sitemap.xml utils

- packages/basic-crawler/src/internals/basic-crawler.ts
- packages/browser-crawler/src/internals/browser-crawler.ts
- packages/http-crawler/src/internals/http-crawler.ts
> feat: log cause with `retryOnBlocked`

- packages/core/src/storages/request_provider.ts
- packages/core/src/storages/request_queue_v2.ts
> fix(RequestQueue): always clear locks when a request is reclaimed

- docs/introduction/01-setting-up.mdx
- docs/introduction/02-first-crawler.mdx
- docs/introduction/03-adding-urls.mdx
- docs/introduction/04-real-world-project.mdx
- docs/introduction/05-crawling.mdx
- docs/introduction/06-scraping.mdx
- docs/introduction/07-saving-data.mdx
- docs/introduction/08-refactoring.mdx
- docs/introduction/09-deployment.mdx
- docs/introduction/index.mdx
fix mdlint issues
fix unnecesarry spaces and empty lines
rephrase prose
add titles to notes
> docs: introduction rewrites

- website/blog/2024-02-22-launching-crawlee-blog.md
> docs: update 2024-02-22-launching-crawlee-blog.md

- docs/experiments/request_locking.mdx
- packages/core/src/storages/request_provider.ts
- packages/core/src/storages/request_queue.ts
- packages/core/src/storages/request_queue_v2.ts
- website/versioned_docs/version-3.5/experiments/request_locking.mdx
- website/versioned_docs/version-3.6/experiments/request_locking.mdx
- website/versioned_docs/version-3.7/experiments/request_locking.mdx
- website/versioned_docs/version-3.8/experiments/request_locking.mdx
Context: https://apify.slack.com/archives/CD0SF6KD4/p1709217047575549
> fix(core): solve possible dead locks in `RequestQueueV2`

- website/docusaurus.config.js
Added meta title and description to Crawlee blog.
> docs: add meta title and description

- packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts
- test/core/puppeteer_utils.test.ts
> fix(puppeteer): allow passing `networkidle` to `waitUntil` in `gotoExtended`

- test/e2e/playwright-enqueue-links/actor/main.js
- test/e2e/playwright-enqueue-links/test.mjs
https://github.com/apify/crawlee/actions/runs/8568760772/job/23483277114
> test: fix e2e tests after yet another store redesign

- website/blog/2024/04-23-scrapy-vs-crawlee/index.md
> docs: fixes

- packages/utils/src/internals/sitemap.ts
- packages/utils/test/sitemap.test.ts
> feat: Loading sitemaps from string

- packages/memory-storage/src/fs/key-value-store/fs.ts
- packages/memory-storage/test/key-value-store/with-extension.test.ts
> fix: improve fix for double extension in KVS with HTML files

- README.md
- website/docusaurus.config.js
add webinar to announcement bar and readme.
> docs: add note about webinar to the docs and readme

- packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
The adaptive crawler runs some request handlers twice, once via HTTP client and once via browser. Previously, both of those request handler executions were producing logs. Now the logging for the HTTP client execution (which is optional) is proxied and only executed when the execution gets committed, or an error is thrown. Logging of the browser-based execution is left intact, since the results from that are always committed.
> fix(adaptive-crawler): log only once for the committed request handler execution

- packages/core/src/proxy_configuration.ts
Logs the domain and original / new proxy tier whenever the tier is changing.
> docs: proxy tier logging

- website/docusaurus.config.js
> docs: improve banner

- packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
The crawler state provided in `useState` is now cloned before we run the browser, and the old state is used for the HTTP based rerun, so it can produce the same results. Since we only do this for the reruns, we don't need to care about persistence of the state, we only check for the detection outcome.
> fix: fix detection of HTTP site when using the `useState` in adaptive crawler

- website/src/pages/index.js
remove the launch yc button
slack convo: https://apify.slack.com/archives/C03NESUMYQN/p1720706606120589
> docs: remove yc launch button

- website/docusaurus.config.js
changed the announcement to webinar
> docs: change announcement bar

- docs/examples/crawl_all_links.mdx
- docs/examples/crawl_sitemap.mdx
- docs/examples/crawler-plugins/index.mdx
- docs/examples/forms.mdx
- docs/examples/http_crawler.mdx
- docs/examples/puppeteer_capture_screenshot.mdx
- docs/guides/cheerio_crawler.mdx
- website/versioned_docs/version-3.11/examples/crawl_all_links.mdx
- website/versioned_docs/version-3.11/examples/crawl_sitemap.mdx
- website/versioned_docs/version-3.11/examples/crawler-plugins/index.mdx
- website/versioned_docs/version-3.11/examples/forms.mdx
- website/versioned_docs/version-3.11/examples/http_crawler.mdx
- website/versioned_docs/version-3.11/examples/puppeteer_capture_screenshot.mdx
- website/versioned_docs/version-3.11/guides/cheerio_crawler.mdx
changes for seo in examples and guides
> docs: seo changes

- website/docusaurus.config.js
> docs: shorter copy

- packages/memory-storage/src/fs/request-queue/fs.ts
- packages/memory-storage/src/fs/request-queue/index.ts
- packages/memory-storage/src/fs/request-queue/memory.ts
- packages/memory-storage/src/resource-clients/request-queue.ts
> chore: try to reduce fs calls for listing heads

- website/docusaurus.config.js
> docs: remove banner

- website/blog/2024/08-27-how-to-scrape-infinite-scrolling-pages/index.md
Add embedded webinar as requested by marketing.
> docs: video-embed

- website/docusaurus.config.js
Adding a script that loads Intercom messenger which we can use for AI chat bot.
> docs: add intercom messenger

- website/blog/2024/07-05-launching-crawlee-python/index.md
- website/blog/2024/08-27-how-to-scrape-infinite-scrolling-pages/index.md
Closes: https://github.com/apify/crawlee-python/issues/509
> docs: changes regarding the updated structure of py templates

- packages/utils/src/internals/sitemap.ts
- packages/utils/test/sitemap.test.ts
> fix: `.trim()` urls from pretty-printed sitemap.xml files

- website/blog/2024/11-15-graphql-persisted-query/index.md
> docs: fix og image

- packages/utils/src/internals/social.ts
- test/utils/social.test.ts
> fix(social): support new URL formats for Facebook, YouTube and X

- test/e2e/playwright-enqueue-links-base/test.mjs
https://github.com/apify/crawlee/actions/runs/13245598855
> test: skip flaky e2e test

- test/e2e/cheerio-default-ts/actor/main.ts
- test/e2e/cheerio-default/actor/main.js
- test/e2e/cheerio-max-requests/actor/main.js
- test/e2e/cheerio-page-info/actor/main.js
- test/e2e/cheerio-request-queue-v2/actor/main.js
- test/e2e/cheerio-stop-resume-ts/actor/main.ts
- test/e2e/jsdom-default-ts/actor/main.ts
- test/e2e/linkedom-default-ts/actor/main.ts
- test/e2e/playwright-default/actor/main.js
- test/e2e/playwright-multi-run/actor/main.js
- test/e2e/puppeteer-default/actor/main.js
Runs e2e tests against the correct documentation URLs after the recent redesign.
> chore(e2e): fix tests after the documentation redesign

- packages/basic-crawler/src/internals/basic-crawler.ts
- packages/browser-crawler/src/internals/browser-crawler.ts
- packages/cheerio-crawler/src/internals/cheerio-crawler.ts
- packages/core/src/enqueue_links/enqueue_links.ts
- packages/jsdom-crawler/src/internals/jsdom-crawler.ts
- packages/linkedom-crawler/src/internals/linkedom-crawler.ts
- test/e2e/adaptive-playwright-robots-file/actor/.actor/actor.json
- test/e2e/adaptive-playwright-robots-file/actor/.gitignore
- test/e2e/adaptive-playwright-robots-file/actor/Dockerfile
- test/e2e/adaptive-playwright-robots-file/actor/main.js
- test/e2e/adaptive-playwright-robots-file/actor/package.json
- test/e2e/adaptive-playwright-robots-file/test.mjs
- test/e2e/tools.mjs
> feat: add `onSkippedRequest` option

- packages/browser-pool/src/anonymize-proxy.ts
- packages/browser-pool/test/tsconfig.json
- test/browser-pool/anonymize-proxy-sugar.test.ts
> fix: Fix trailing slash removal in BrowserPool

- packages/core/src/storages/sitemap_request_list.ts
> fix: Persist SitemapRequestList state periodically

- packages/basic-crawler/src/internals/basic-crawler.ts
- test/core/crawlers/basic_crawler.test.ts
> fix: respect `autoscaledPoolOptions.isTaskReadyFunction` option

- scripts/typescript_fixes.mjs
> fix: convert `@apilink` to `@link` on build

- packages/browser-pool/src/browser-pool.ts
> fix: await `_createPageForBrowser` in browser pool

- test/e2e/cheerio-default-ts/actor/tsconfig.json
- test/e2e/cheerio-impit-ts/actor/tsconfig.json
- test/e2e/cheerio-stop-resume-ts/actor/tsconfig.json
- test/e2e/jsdom-default-ts/actor/tsconfig.json
- test/e2e/jsdom-react-ts/actor/tsconfig.json
- test/e2e/linkedom-default-ts/actor/tsconfig.json
Will run e2e tests myself, please stand by while I rebuild images :loading:
> chore(ci): fix e2e tests

- packages/impit-client/package.json
- packages/impit-client/src/index.ts
- yarn.lock
Switches `@crawlee/impit-client` to the latest `impit` version.
> feat(impit-client): bump `impit` version to v0.4

- packages/basic-crawler/src/internals/basic-crawler.ts
- packages/core/src/storages/request_queue_v2.ts
- related to https://github.com/apify/apify-sdk-js/issues/392
> fix: Optimize request unlocking to get rid of unnecessary unlock calls

- .github/workflows/test-e2e.yml
- test/e2e/cheerio-curl-impersonate-ts/actor/main.ts
- test/e2e/cheerio-impit-ts/actor/main.ts
Related to https://github.com/apify/crawlee/issues/2906 .
> chore: use self-hosted httpbin instance in e2e tests

- packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
- this is necessary for some more complex comparisons - if the request handler decides to bail out early, for instance, we don't want to pollute our rendering type predictor with that.
> feat: Allow the AdaptivePlaywrightCrawler result comparator to signal an inconclusive result

- packages/playwright-crawler/src/internals/utils/rendering-type-prediction.ts
- test/core/crawlers/adaptive_playwright_crawler.test.ts
Fixes a bug uncovered by [E2E tests](https://github.com/apify/crawlee/actions/runs/15600211879/job/43938591340)
> refactor: Fix rendering type detection persistence

- test/e2e/playwright-multi-run/actor/main.js
- test/e2e/playwright-multi-run/test.mjs
Fixes issue discovered in https://github.com/apify/crawlee/actions/runs/15606941506/job/43958568134
> test: Update fix-playwright-multi-run e2e test

- packages/basic-crawler/src/internals/basic-crawler.ts
- packages/browser-crawler/src/internals/browser-crawler.ts
- packages/core/src/enqueue_links/enqueue_links.ts
- packages/core/src/enqueue_links/shared.ts
- packages/http-crawler/src/internals/http-crawler.ts
- packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
> feat: Report links skipped because of various filter conditions

- website/docusaurus.config.js
- website/package.json
> docs: Add link to Python documentation to llms.txt
